// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module integrated_gcn_approx_spmm_compute_Pipeline_SPMM_WRITE (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        result_fifo_din,
        result_fifo_full_n,
        result_fifo_write,
        result_fifo_num_data_valid,
        result_fifo_fifo_cap,
        acc_address0,
        acc_ce0,
        acc_q0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_q0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_q0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_q0,
        acc_4_address0,
        acc_4_ce0,
        acc_4_q0,
        acc_5_address0,
        acc_5_ce0,
        acc_5_q0,
        acc_6_address0,
        acc_6_ce0,
        acc_6_q0,
        acc_7_address0,
        acc_7_ce0,
        acc_7_q0,
        acc_8_address0,
        acc_8_ce0,
        acc_8_q0,
        acc_9_address0,
        acc_9_ce0,
        acc_9_q0,
        acc_10_address0,
        acc_10_ce0,
        acc_10_q0,
        acc_11_address0,
        acc_11_ce0,
        acc_11_q0,
        acc_12_address0,
        acc_12_ce0,
        acc_12_q0,
        acc_13_address0,
        acc_13_ce0,
        acc_13_q0,
        acc_14_address0,
        acc_14_ce0,
        acc_14_q0,
        acc_15_address0,
        acc_15_ce0,
        acc_15_q0,
        acc_16_address0,
        acc_16_ce0,
        acc_16_q0,
        acc_17_address0,
        acc_17_ce0,
        acc_17_q0,
        acc_18_address0,
        acc_18_ce0,
        acc_18_q0,
        acc_19_address0,
        acc_19_ce0,
        acc_19_q0,
        acc_20_address0,
        acc_20_ce0,
        acc_20_q0,
        acc_21_address0,
        acc_21_ce0,
        acc_21_q0,
        acc_22_address0,
        acc_22_ce0,
        acc_22_q0,
        acc_23_address0,
        acc_23_ce0,
        acc_23_q0,
        acc_24_address0,
        acc_24_ce0,
        acc_24_q0,
        acc_25_address0,
        acc_25_ce0,
        acc_25_q0,
        acc_26_address0,
        acc_26_ce0,
        acc_26_q0,
        acc_27_address0,
        acc_27_ce0,
        acc_27_q0,
        acc_28_address0,
        acc_28_ce0,
        acc_28_q0,
        acc_29_address0,
        acc_29_ce0,
        acc_29_q0,
        acc_30_address0,
        acc_30_ce0,
        acc_30_q0,
        acc_31_address0,
        acc_31_ce0,
        acc_31_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] result_fifo_din;
input   result_fifo_full_n;
output   result_fifo_write;
input  [31:0] result_fifo_num_data_valid;
input  [31:0] result_fifo_fifo_cap;
output  [0:0] acc_address0;
output   acc_ce0;
input  [15:0] acc_q0;
output  [0:0] acc_1_address0;
output   acc_1_ce0;
input  [15:0] acc_1_q0;
output  [0:0] acc_2_address0;
output   acc_2_ce0;
input  [15:0] acc_2_q0;
output  [0:0] acc_3_address0;
output   acc_3_ce0;
input  [15:0] acc_3_q0;
output  [0:0] acc_4_address0;
output   acc_4_ce0;
input  [15:0] acc_4_q0;
output  [0:0] acc_5_address0;
output   acc_5_ce0;
input  [15:0] acc_5_q0;
output  [0:0] acc_6_address0;
output   acc_6_ce0;
input  [15:0] acc_6_q0;
output  [0:0] acc_7_address0;
output   acc_7_ce0;
input  [15:0] acc_7_q0;
output  [0:0] acc_8_address0;
output   acc_8_ce0;
input  [15:0] acc_8_q0;
output  [0:0] acc_9_address0;
output   acc_9_ce0;
input  [15:0] acc_9_q0;
output  [0:0] acc_10_address0;
output   acc_10_ce0;
input  [15:0] acc_10_q0;
output  [0:0] acc_11_address0;
output   acc_11_ce0;
input  [15:0] acc_11_q0;
output  [0:0] acc_12_address0;
output   acc_12_ce0;
input  [15:0] acc_12_q0;
output  [0:0] acc_13_address0;
output   acc_13_ce0;
input  [15:0] acc_13_q0;
output  [0:0] acc_14_address0;
output   acc_14_ce0;
input  [15:0] acc_14_q0;
output  [0:0] acc_15_address0;
output   acc_15_ce0;
input  [15:0] acc_15_q0;
output  [0:0] acc_16_address0;
output   acc_16_ce0;
input  [15:0] acc_16_q0;
output  [0:0] acc_17_address0;
output   acc_17_ce0;
input  [15:0] acc_17_q0;
output  [0:0] acc_18_address0;
output   acc_18_ce0;
input  [15:0] acc_18_q0;
output  [0:0] acc_19_address0;
output   acc_19_ce0;
input  [15:0] acc_19_q0;
output  [0:0] acc_20_address0;
output   acc_20_ce0;
input  [15:0] acc_20_q0;
output  [0:0] acc_21_address0;
output   acc_21_ce0;
input  [15:0] acc_21_q0;
output  [0:0] acc_22_address0;
output   acc_22_ce0;
input  [15:0] acc_22_q0;
output  [0:0] acc_23_address0;
output   acc_23_ce0;
input  [15:0] acc_23_q0;
output  [0:0] acc_24_address0;
output   acc_24_ce0;
input  [15:0] acc_24_q0;
output  [0:0] acc_25_address0;
output   acc_25_ce0;
input  [15:0] acc_25_q0;
output  [0:0] acc_26_address0;
output   acc_26_ce0;
input  [15:0] acc_26_q0;
output  [0:0] acc_27_address0;
output   acc_27_ce0;
input  [15:0] acc_27_q0;
output  [0:0] acc_28_address0;
output   acc_28_ce0;
input  [15:0] acc_28_q0;
output  [0:0] acc_29_address0;
output   acc_29_ce0;
input  [15:0] acc_29_q0;
output  [0:0] acc_30_address0;
output   acc_30_ce0;
input  [15:0] acc_30_q0;
output  [0:0] acc_31_address0;
output   acc_31_ce0;
input  [15:0] acc_31_q0;

reg ap_idle;
reg result_fifo_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln265_fu_639_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    result_fifo_blk_n;
wire    ap_block_pp0_stage0;
wire   [4:0] trunc_ln265_fu_651_p1;
reg   [4:0] trunc_ln265_reg_1060;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln265_fu_663_p1;
reg   [6:0] f_fu_204;
wire   [6:0] add_ln265_fu_645_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_f_1;
reg    ap_block_pp0_stage0_01001;
reg    acc_ce0_local;
reg    acc_1_ce0_local;
reg    acc_2_ce0_local;
reg    acc_3_ce0_local;
reg    acc_4_ce0_local;
reg    acc_5_ce0_local;
reg    acc_6_ce0_local;
reg    acc_7_ce0_local;
reg    acc_8_ce0_local;
reg    acc_9_ce0_local;
reg    acc_10_ce0_local;
reg    acc_11_ce0_local;
reg    acc_12_ce0_local;
reg    acc_13_ce0_local;
reg    acc_14_ce0_local;
reg    acc_15_ce0_local;
reg    acc_16_ce0_local;
reg    acc_17_ce0_local;
reg    acc_18_ce0_local;
reg    acc_19_ce0_local;
reg    acc_20_ce0_local;
reg    acc_21_ce0_local;
reg    acc_22_ce0_local;
reg    acc_23_ce0_local;
reg    acc_24_ce0_local;
reg    acc_25_ce0_local;
reg    acc_26_ce0_local;
reg    acc_27_ce0_local;
reg    acc_28_ce0_local;
reg    acc_29_ce0_local;
reg    acc_30_ce0_local;
reg    acc_31_ce0_local;
wire   [0:0] tmp_fu_655_p3;
wire   [15:0] tmp_s_fu_704_p65;
wire   [15:0] tmp_s_fu_704_p67;
wire   [0:0] tmp_2_fu_857_p3;
wire   [7:0] trunc_ln3_fu_847_p4;
wire   [7:0] zext_ln267_fu_873_p1;
wire   [7:0] add_ln267_fu_877_p2;
wire   [0:0] tmp_4_fu_883_p3;
wire   [0:0] tmp_3_fu_865_p3;
wire   [0:0] xor_ln267_fu_891_p2;
wire   [1:0] tmp_6_fu_911_p3;
wire   [2:0] tmp_7_fu_925_p3;
wire   [0:0] and_ln267_fu_897_p2;
wire   [0:0] icmp_ln267_1_fu_933_p2;
wire   [0:0] icmp_ln267_2_fu_939_p2;
wire   [0:0] tmp_5_fu_903_p3;
wire   [0:0] icmp_ln267_fu_919_p2;
wire   [0:0] xor_ln267_1_fu_953_p2;
wire   [0:0] and_ln267_1_fu_959_p2;
wire   [0:0] select_ln267_fu_945_p3;
wire   [0:0] xor_ln267_2_fu_979_p2;
wire   [0:0] tmp_1_fu_839_p3;
wire   [0:0] or_ln267_fu_985_p2;
wire   [0:0] xor_ln267_3_fu_991_p2;
wire   [0:0] select_ln267_1_fu_965_p3;
wire   [0:0] and_ln267_2_fu_973_p2;
wire   [0:0] and_ln267_4_fu_1003_p2;
wire   [0:0] or_ln267_2_fu_1009_p2;
wire   [0:0] xor_ln267_4_fu_1015_p2;
wire   [0:0] and_ln267_3_fu_997_p2;
wire   [0:0] and_ln267_5_fu_1021_p2;
wire   [0:0] or_ln267_1_fu_1035_p2;
wire   [7:0] select_ln267_2_fu_1027_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [4:0] tmp_s_fu_704_p1;
wire   [4:0] tmp_s_fu_704_p3;
wire   [4:0] tmp_s_fu_704_p5;
wire   [4:0] tmp_s_fu_704_p7;
wire   [4:0] tmp_s_fu_704_p9;
wire   [4:0] tmp_s_fu_704_p11;
wire   [4:0] tmp_s_fu_704_p13;
wire   [4:0] tmp_s_fu_704_p15;
wire   [4:0] tmp_s_fu_704_p17;
wire   [4:0] tmp_s_fu_704_p19;
wire   [4:0] tmp_s_fu_704_p21;
wire   [4:0] tmp_s_fu_704_p23;
wire   [4:0] tmp_s_fu_704_p25;
wire   [4:0] tmp_s_fu_704_p27;
wire   [4:0] tmp_s_fu_704_p29;
wire   [4:0] tmp_s_fu_704_p31;
wire  signed [4:0] tmp_s_fu_704_p33;
wire  signed [4:0] tmp_s_fu_704_p35;
wire  signed [4:0] tmp_s_fu_704_p37;
wire  signed [4:0] tmp_s_fu_704_p39;
wire  signed [4:0] tmp_s_fu_704_p41;
wire  signed [4:0] tmp_s_fu_704_p43;
wire  signed [4:0] tmp_s_fu_704_p45;
wire  signed [4:0] tmp_s_fu_704_p47;
wire  signed [4:0] tmp_s_fu_704_p49;
wire  signed [4:0] tmp_s_fu_704_p51;
wire  signed [4:0] tmp_s_fu_704_p53;
wire  signed [4:0] tmp_s_fu_704_p55;
wire  signed [4:0] tmp_s_fu_704_p57;
wire  signed [4:0] tmp_s_fu_704_p59;
wire  signed [4:0] tmp_s_fu_704_p61;
wire  signed [4:0] tmp_s_fu_704_p63;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 f_fu_204 = 7'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) integrated_gcn_approx_sparsemux_65_5_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 5'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 5'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 5'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 5'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 5'h4 ),
    .din4_WIDTH( 16 ),
    .CASE5( 5'h5 ),
    .din5_WIDTH( 16 ),
    .CASE6( 5'h6 ),
    .din6_WIDTH( 16 ),
    .CASE7( 5'h7 ),
    .din7_WIDTH( 16 ),
    .CASE8( 5'h8 ),
    .din8_WIDTH( 16 ),
    .CASE9( 5'h9 ),
    .din9_WIDTH( 16 ),
    .CASE10( 5'hA ),
    .din10_WIDTH( 16 ),
    .CASE11( 5'hB ),
    .din11_WIDTH( 16 ),
    .CASE12( 5'hC ),
    .din12_WIDTH( 16 ),
    .CASE13( 5'hD ),
    .din13_WIDTH( 16 ),
    .CASE14( 5'hE ),
    .din14_WIDTH( 16 ),
    .CASE15( 5'hF ),
    .din15_WIDTH( 16 ),
    .CASE16( 5'h10 ),
    .din16_WIDTH( 16 ),
    .CASE17( 5'h11 ),
    .din17_WIDTH( 16 ),
    .CASE18( 5'h12 ),
    .din18_WIDTH( 16 ),
    .CASE19( 5'h13 ),
    .din19_WIDTH( 16 ),
    .CASE20( 5'h14 ),
    .din20_WIDTH( 16 ),
    .CASE21( 5'h15 ),
    .din21_WIDTH( 16 ),
    .CASE22( 5'h16 ),
    .din22_WIDTH( 16 ),
    .CASE23( 5'h17 ),
    .din23_WIDTH( 16 ),
    .CASE24( 5'h18 ),
    .din24_WIDTH( 16 ),
    .CASE25( 5'h19 ),
    .din25_WIDTH( 16 ),
    .CASE26( 5'h1A ),
    .din26_WIDTH( 16 ),
    .CASE27( 5'h1B ),
    .din27_WIDTH( 16 ),
    .CASE28( 5'h1C ),
    .din28_WIDTH( 16 ),
    .CASE29( 5'h1D ),
    .din29_WIDTH( 16 ),
    .CASE30( 5'h1E ),
    .din30_WIDTH( 16 ),
    .CASE31( 5'h1F ),
    .din31_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 5 ),
    .dout_WIDTH( 16 ))
sparsemux_65_5_16_1_1_U987(
    .din0(acc_q0),
    .din1(acc_1_q0),
    .din2(acc_2_q0),
    .din3(acc_3_q0),
    .din4(acc_4_q0),
    .din5(acc_5_q0),
    .din6(acc_6_q0),
    .din7(acc_7_q0),
    .din8(acc_8_q0),
    .din9(acc_9_q0),
    .din10(acc_10_q0),
    .din11(acc_11_q0),
    .din12(acc_12_q0),
    .din13(acc_13_q0),
    .din14(acc_14_q0),
    .din15(acc_15_q0),
    .din16(acc_16_q0),
    .din17(acc_17_q0),
    .din18(acc_18_q0),
    .din19(acc_19_q0),
    .din20(acc_20_q0),
    .din21(acc_21_q0),
    .din22(acc_22_q0),
    .din23(acc_23_q0),
    .din24(acc_24_q0),
    .din25(acc_25_q0),
    .din26(acc_26_q0),
    .din27(acc_27_q0),
    .din28(acc_28_q0),
    .din29(acc_29_q0),
    .din30(acc_30_q0),
    .din31(acc_31_q0),
    .def(tmp_s_fu_704_p65),
    .sel(trunc_ln265_reg_1060),
    .dout(tmp_s_fu_704_p67)
);

integrated_gcn_approx_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln265_fu_639_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            f_fu_204 <= add_ln265_fu_645_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            f_fu_204 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln265_reg_1060 <= trunc_ln265_fu_651_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_10_ce0_local = 1'b1;
    end else begin
        acc_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_11_ce0_local = 1'b1;
    end else begin
        acc_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_12_ce0_local = 1'b1;
    end else begin
        acc_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_13_ce0_local = 1'b1;
    end else begin
        acc_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_14_ce0_local = 1'b1;
    end else begin
        acc_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_15_ce0_local = 1'b1;
    end else begin
        acc_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_16_ce0_local = 1'b1;
    end else begin
        acc_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_17_ce0_local = 1'b1;
    end else begin
        acc_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_18_ce0_local = 1'b1;
    end else begin
        acc_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_19_ce0_local = 1'b1;
    end else begin
        acc_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_1_ce0_local = 1'b1;
    end else begin
        acc_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_20_ce0_local = 1'b1;
    end else begin
        acc_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_21_ce0_local = 1'b1;
    end else begin
        acc_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_22_ce0_local = 1'b1;
    end else begin
        acc_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_23_ce0_local = 1'b1;
    end else begin
        acc_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_24_ce0_local = 1'b1;
    end else begin
        acc_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_25_ce0_local = 1'b1;
    end else begin
        acc_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_26_ce0_local = 1'b1;
    end else begin
        acc_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_27_ce0_local = 1'b1;
    end else begin
        acc_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_28_ce0_local = 1'b1;
    end else begin
        acc_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_29_ce0_local = 1'b1;
    end else begin
        acc_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_2_ce0_local = 1'b1;
    end else begin
        acc_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_30_ce0_local = 1'b1;
    end else begin
        acc_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_31_ce0_local = 1'b1;
    end else begin
        acc_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_3_ce0_local = 1'b1;
    end else begin
        acc_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_4_ce0_local = 1'b1;
    end else begin
        acc_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_5_ce0_local = 1'b1;
    end else begin
        acc_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_6_ce0_local = 1'b1;
    end else begin
        acc_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_7_ce0_local = 1'b1;
    end else begin
        acc_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_8_ce0_local = 1'b1;
    end else begin
        acc_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_9_ce0_local = 1'b1;
    end else begin
        acc_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_ce0_local = 1'b1;
    end else begin
        acc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln265_fu_639_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_f_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_f_1 = f_fu_204;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_fifo_blk_n = result_fifo_full_n;
    end else begin
        result_fifo_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_fifo_write = 1'b1;
    end else begin
        result_fifo_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_address0 = zext_ln265_fu_663_p1;

assign acc_10_ce0 = acc_10_ce0_local;

assign acc_11_address0 = zext_ln265_fu_663_p1;

assign acc_11_ce0 = acc_11_ce0_local;

assign acc_12_address0 = zext_ln265_fu_663_p1;

assign acc_12_ce0 = acc_12_ce0_local;

assign acc_13_address0 = zext_ln265_fu_663_p1;

assign acc_13_ce0 = acc_13_ce0_local;

assign acc_14_address0 = zext_ln265_fu_663_p1;

assign acc_14_ce0 = acc_14_ce0_local;

assign acc_15_address0 = zext_ln265_fu_663_p1;

assign acc_15_ce0 = acc_15_ce0_local;

assign acc_16_address0 = zext_ln265_fu_663_p1;

assign acc_16_ce0 = acc_16_ce0_local;

assign acc_17_address0 = zext_ln265_fu_663_p1;

assign acc_17_ce0 = acc_17_ce0_local;

assign acc_18_address0 = zext_ln265_fu_663_p1;

assign acc_18_ce0 = acc_18_ce0_local;

assign acc_19_address0 = zext_ln265_fu_663_p1;

assign acc_19_ce0 = acc_19_ce0_local;

assign acc_1_address0 = zext_ln265_fu_663_p1;

assign acc_1_ce0 = acc_1_ce0_local;

assign acc_20_address0 = zext_ln265_fu_663_p1;

assign acc_20_ce0 = acc_20_ce0_local;

assign acc_21_address0 = zext_ln265_fu_663_p1;

assign acc_21_ce0 = acc_21_ce0_local;

assign acc_22_address0 = zext_ln265_fu_663_p1;

assign acc_22_ce0 = acc_22_ce0_local;

assign acc_23_address0 = zext_ln265_fu_663_p1;

assign acc_23_ce0 = acc_23_ce0_local;

assign acc_24_address0 = zext_ln265_fu_663_p1;

assign acc_24_ce0 = acc_24_ce0_local;

assign acc_25_address0 = zext_ln265_fu_663_p1;

assign acc_25_ce0 = acc_25_ce0_local;

assign acc_26_address0 = zext_ln265_fu_663_p1;

assign acc_26_ce0 = acc_26_ce0_local;

assign acc_27_address0 = zext_ln265_fu_663_p1;

assign acc_27_ce0 = acc_27_ce0_local;

assign acc_28_address0 = zext_ln265_fu_663_p1;

assign acc_28_ce0 = acc_28_ce0_local;

assign acc_29_address0 = zext_ln265_fu_663_p1;

assign acc_29_ce0 = acc_29_ce0_local;

assign acc_2_address0 = zext_ln265_fu_663_p1;

assign acc_2_ce0 = acc_2_ce0_local;

assign acc_30_address0 = zext_ln265_fu_663_p1;

assign acc_30_ce0 = acc_30_ce0_local;

assign acc_31_address0 = zext_ln265_fu_663_p1;

assign acc_31_ce0 = acc_31_ce0_local;

assign acc_3_address0 = zext_ln265_fu_663_p1;

assign acc_3_ce0 = acc_3_ce0_local;

assign acc_4_address0 = zext_ln265_fu_663_p1;

assign acc_4_ce0 = acc_4_ce0_local;

assign acc_5_address0 = zext_ln265_fu_663_p1;

assign acc_5_ce0 = acc_5_ce0_local;

assign acc_6_address0 = zext_ln265_fu_663_p1;

assign acc_6_ce0 = acc_6_ce0_local;

assign acc_7_address0 = zext_ln265_fu_663_p1;

assign acc_7_ce0 = acc_7_ce0_local;

assign acc_8_address0 = zext_ln265_fu_663_p1;

assign acc_8_ce0 = acc_8_ce0_local;

assign acc_9_address0 = zext_ln265_fu_663_p1;

assign acc_9_ce0 = acc_9_ce0_local;

assign acc_address0 = zext_ln265_fu_663_p1;

assign acc_ce0 = acc_ce0_local;

assign add_ln265_fu_645_p2 = (ap_sig_allocacmp_f_1 + 7'd1);

assign add_ln267_fu_877_p2 = (trunc_ln3_fu_847_p4 + zext_ln267_fu_873_p1);

assign and_ln267_1_fu_959_p2 = (xor_ln267_1_fu_953_p2 & icmp_ln267_fu_919_p2);

assign and_ln267_2_fu_973_p2 = (icmp_ln267_1_fu_933_p2 & and_ln267_fu_897_p2);

assign and_ln267_3_fu_997_p2 = (xor_ln267_3_fu_991_p2 & or_ln267_fu_985_p2);

assign and_ln267_4_fu_1003_p2 = (tmp_4_fu_883_p3 & select_ln267_1_fu_965_p3);

assign and_ln267_5_fu_1021_p2 = (xor_ln267_4_fu_1015_p2 & tmp_1_fu_839_p3);

assign and_ln267_fu_897_p2 = (xor_ln267_fu_891_p2 & tmp_3_fu_865_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (result_fifo_full_n == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln265_fu_639_p2 = ((ap_sig_allocacmp_f_1 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln267_1_fu_933_p2 = ((tmp_7_fu_925_p3 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln267_2_fu_939_p2 = ((tmp_7_fu_925_p3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln267_fu_919_p2 = ((tmp_6_fu_911_p3 == 2'd3) ? 1'b1 : 1'b0);

assign or_ln267_1_fu_1035_p2 = (and_ln267_5_fu_1021_p2 | and_ln267_3_fu_997_p2);

assign or_ln267_2_fu_1009_p2 = (and_ln267_4_fu_1003_p2 | and_ln267_2_fu_973_p2);

assign or_ln267_fu_985_p2 = (xor_ln267_2_fu_979_p2 | tmp_4_fu_883_p3);

assign result_fifo_din = ((or_ln267_1_fu_1035_p2[0:0] == 1'b1) ? select_ln267_2_fu_1027_p3 : add_ln267_fu_877_p2);

assign select_ln267_1_fu_965_p3 = ((and_ln267_fu_897_p2[0:0] == 1'b1) ? and_ln267_1_fu_959_p2 : icmp_ln267_1_fu_933_p2);

assign select_ln267_2_fu_1027_p3 = ((and_ln267_3_fu_997_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln267_fu_945_p3 = ((and_ln267_fu_897_p2[0:0] == 1'b1) ? icmp_ln267_1_fu_933_p2 : icmp_ln267_2_fu_939_p2);

assign tmp_1_fu_839_p3 = tmp_s_fu_704_p67[32'd15];

assign tmp_2_fu_857_p3 = tmp_s_fu_704_p67[32'd4];

assign tmp_3_fu_865_p3 = tmp_s_fu_704_p67[32'd12];

assign tmp_4_fu_883_p3 = add_ln267_fu_877_p2[32'd7];

assign tmp_5_fu_903_p3 = tmp_s_fu_704_p67[32'd13];

assign tmp_6_fu_911_p3 = {{tmp_s_fu_704_p67[15:14]}};

assign tmp_7_fu_925_p3 = {{tmp_s_fu_704_p67[15:13]}};

assign tmp_fu_655_p3 = ap_sig_allocacmp_f_1[32'd5];

assign tmp_s_fu_704_p65 = 'bx;

assign trunc_ln265_fu_651_p1 = ap_sig_allocacmp_f_1[4:0];

assign trunc_ln3_fu_847_p4 = {{tmp_s_fu_704_p67[12:5]}};

assign xor_ln267_1_fu_953_p2 = (tmp_5_fu_903_p3 ^ 1'd1);

assign xor_ln267_2_fu_979_p2 = (select_ln267_fu_945_p3 ^ 1'd1);

assign xor_ln267_3_fu_991_p2 = (tmp_1_fu_839_p3 ^ 1'd1);

assign xor_ln267_4_fu_1015_p2 = (or_ln267_2_fu_1009_p2 ^ 1'd1);

assign xor_ln267_fu_891_p2 = (tmp_4_fu_883_p3 ^ 1'd1);

assign zext_ln265_fu_663_p1 = tmp_fu_655_p3;

assign zext_ln267_fu_873_p1 = tmp_2_fu_857_p3;

endmodule //integrated_gcn_approx_spmm_compute_Pipeline_SPMM_WRITE
