-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity integrated_gcn_approx_spmm_store is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    result_fifo_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    result_fifo_empty_n : IN STD_LOGIC;
    result_fifo_read : OUT STD_LOGIC;
    result_fifo_num_data_valid : IN STD_LOGIC_VECTOR (5 downto 0);
    result_fifo_fifo_cap : IN STD_LOGIC_VECTOR (5 downto 0);
    m_axi_gmem6_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem6_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem6_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_WREADY : IN STD_LOGIC;
    m_axi_gmem6_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem6_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem6_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem6_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem6_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem6_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem6_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem6_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem6_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RVALID : IN STD_LOGIC;
    m_axi_gmem6_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem6_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem6_0_RLAST : IN STD_LOGIC;
    m_axi_gmem6_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem6_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_BVALID : IN STD_LOGIC;
    m_axi_gmem6_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem6_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem6_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem6_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    H_out : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of integrated_gcn_approx_spmm_store is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_FFFFFFFFFFFFFFFF : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111111111111111111111111111111111111111111111111111111";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv18_2A500 : STD_LOGIC_VECTOR (17 downto 0) := "101010010100000000";
    constant ap_const_lv18_1 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv7_3F : STD_LOGIC_VECTOR (6 downto 0) := "0111111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv512_lc_3 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011111111";
    constant ap_const_lv512_lc_4 : STD_LOGIC_VECTOR (511 downto 0) := "11111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln286_reg_392 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_io_grp1 : BOOLEAN;
    signal icmp_ln286_reg_392_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal icmp_ln286_reg_392_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state8_pp0_stage0_iter7_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln279_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem6_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal gmem6_blk_n_W : STD_LOGIC;
    signal gmem6_blk_n_B : STD_LOGIC;
    signal result_fifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln287_s_reg_382 : STD_LOGIC_VECTOR (57 downto 0);
    signal trunc_ln285_fu_246_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln285_reg_387 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln285_reg_387_pp0_iter1_reg : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln286_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln286_reg_392_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln286_reg_392_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln286_reg_392_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln286_reg_392_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal result_fifo_read_reg_402 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln287_fu_277_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal d_fu_106 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln281_fu_256_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_d_load : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal out_vec_fu_110 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    signal out_vec_1_fu_328_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal i_fu_114 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal select_ln279_fu_210_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (11 downto 0);
    signal indvar_flatten_fu_118 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    signal add_ln279_fu_178_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln281_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln279_1_fu_204_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal shl_ln_fu_218_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln287_fu_226_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln287_fu_230_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln276_fu_196_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln1_fu_290_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln285_fu_297_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal zext_ln285_1_fu_307_p1 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln285_fu_301_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal xor_ln285_fu_316_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal shl_ln285_1_fu_310_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal and_ln285_fu_322_p2 : STD_LOGIC_VECTOR (511 downto 0);
    signal trunc_ln287_fu_334_p1 : STD_LOGIC_VECTOR (503 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_256 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component integrated_gcn_approx_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component integrated_gcn_approx_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    d_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_256)) then
                if ((icmp_ln279_fu_172_p2 = ap_const_lv1_0)) then 
                    d_fu_106 <= add_ln281_fu_256_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    d_fu_106 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_114_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_256)) then
                if ((icmp_ln279_fu_172_p2 = ap_const_lv1_0)) then 
                    i_fu_114 <= select_ln279_fu_210_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_114 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_118_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_256)) then
                if ((icmp_ln279_fu_172_p2 = ap_const_lv1_0)) then 
                    indvar_flatten_fu_118 <= add_ln279_fu_178_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_118 <= ap_const_lv18_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln286_reg_392 <= icmp_ln286_fu_250_p2;
                icmp_ln286_reg_392_pp0_iter1_reg <= icmp_ln286_reg_392;
                trunc_ln285_reg_387 <= trunc_ln285_fu_246_p1;
                trunc_ln285_reg_387_pp0_iter1_reg <= trunc_ln285_reg_387;
                trunc_ln287_s_reg_382 <= add_ln287_fu_230_p2(63 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                icmp_ln286_reg_392_pp0_iter2_reg <= icmp_ln286_reg_392_pp0_iter1_reg;
                icmp_ln286_reg_392_pp0_iter3_reg <= icmp_ln286_reg_392_pp0_iter2_reg;
                icmp_ln286_reg_392_pp0_iter4_reg <= icmp_ln286_reg_392_pp0_iter3_reg;
                icmp_ln286_reg_392_pp0_iter5_reg <= icmp_ln286_reg_392_pp0_iter4_reg;
                icmp_ln286_reg_392_pp0_iter6_reg <= icmp_ln286_reg_392_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                out_vec_fu_110 <= out_vec_1_fu_328_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                result_fifo_read_reg_402 <= result_fifo_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln279_1_fu_204_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv12_1));
    add_ln279_fu_178_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv18_1));
    add_ln281_fu_256_p2 <= std_logic_vector(unsigned(select_ln276_fu_196_p3) + unsigned(ap_const_lv7_1));
    add_ln287_fu_230_p2 <= std_logic_vector(unsigned(zext_ln287_fu_226_p1) + unsigned(H_out));
    and_ln285_fu_322_p2 <= (xor_ln285_fu_316_p2 and out_vec_fu_110);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter7, result_fifo_empty_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state8_pp0_stage0_iter7_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7_grp1)) or ((result_fifo_empty_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, result_fifo_empty_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_io_grp1, ap_block_state3_io_grp1, ap_block_state8_pp0_stage0_iter7_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((result_fifo_empty_n = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io_grp1))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp0_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, result_fifo_empty_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_io_grp1, ap_block_state3_io_grp1, ap_block_state8_pp0_stage0_iter7_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((result_fifo_empty_n = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io_grp1))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter7, result_fifo_empty_n, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_io_grp1, ap_block_state3_io_grp1, ap_block_state8_pp0_stage0_iter7_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7_grp1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((result_fifo_empty_n = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state2_io_grp1))) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_io_grp1_assign_proc : process(m_axi_gmem6_0_AWREADY, icmp_ln286_reg_392)
    begin
                ap_block_state2_io_grp1 <= ((m_axi_gmem6_0_AWREADY = ap_const_logic_0) and (icmp_ln286_reg_392 = ap_const_lv1_1));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_gmem6_0_WREADY, icmp_ln286_reg_392_pp0_iter1_reg)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_gmem6_0_WREADY = ap_const_logic_0) and (icmp_ln286_reg_392_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_block_state8_pp0_stage0_iter7_grp1_assign_proc : process(m_axi_gmem6_0_BVALID, icmp_ln286_reg_392_pp0_iter6_reg)
    begin
                ap_block_state8_pp0_stage0_iter7_grp1 <= ((icmp_ln286_reg_392_pp0_iter6_reg = ap_const_lv1_1) and (m_axi_gmem6_0_BVALID = ap_const_logic_0));
    end process;


    ap_condition_256_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_256 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln279_fu_172_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln279_fu_172_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_d_load_assign_proc : process(ap_CS_fsm_pp0_stage0, d_fu_106, ap_loop_init, ap_block_pp0_stage0, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_d_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_d_load <= d_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, i_fu_114, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_114;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten_fu_118, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv18_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_118;
        end if; 
    end process;


    gmem6_blk_n_AW_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, m_axi_gmem6_0_AWREADY, icmp_ln286_reg_392, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln286_reg_392 = ap_const_lv1_1))) then 
            gmem6_blk_n_AW <= m_axi_gmem6_0_AWREADY;
        else 
            gmem6_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem6_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter7, m_axi_gmem6_0_BVALID, icmp_ln286_reg_392_pp0_iter6_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln286_reg_392_pp0_iter6_reg = ap_const_lv1_1))) then 
            gmem6_blk_n_B <= m_axi_gmem6_0_BVALID;
        else 
            gmem6_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem6_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_gmem6_0_WREADY, icmp_ln286_reg_392_pp0_iter1_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln286_reg_392_pp0_iter1_reg = ap_const_lv1_1))) then 
            gmem6_blk_n_W <= m_axi_gmem6_0_WREADY;
        else 
            gmem6_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln279_fu_172_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv18_2A500) else "0";
    icmp_ln281_fu_190_p2 <= "1" when (ap_sig_allocacmp_d_load = ap_const_lv7_40) else "0";
    icmp_ln286_fu_250_p2 <= "1" when (select_ln276_fu_196_p3 = ap_const_lv7_3F) else "0";
    m_axi_gmem6_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem6_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem6_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem6_0_ARID <= ap_const_lv1_0;
    m_axi_gmem6_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem6_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem6_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem6_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem6_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem6_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem6_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem6_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem6_0_AWADDR <= sext_ln287_fu_277_p1;
    m_axi_gmem6_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem6_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem6_0_AWID <= ap_const_lv1_0;
    m_axi_gmem6_0_AWLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem6_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem6_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem6_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem6_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem6_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem6_0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem6_0_AWVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln286_reg_392, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln286_reg_392 = ap_const_lv1_1))) then 
            m_axi_gmem6_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem6_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem6_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter7, icmp_ln286_reg_392_pp0_iter6_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln286_reg_392_pp0_iter6_reg = ap_const_lv1_1))) then 
            m_axi_gmem6_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem6_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem6_0_RREADY <= ap_const_logic_0;
    m_axi_gmem6_0_WDATA <= (result_fifo_read_reg_402 & trunc_ln287_fu_334_p1);
    m_axi_gmem6_0_WID <= ap_const_lv1_0;
    m_axi_gmem6_0_WLAST <= ap_const_logic_0;
    m_axi_gmem6_0_WSTRB <= ap_const_lv64_FFFFFFFFFFFFFFFF;
    m_axi_gmem6_0_WUSER <= ap_const_lv1_0;

    m_axi_gmem6_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter2, icmp_ln286_reg_392_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln286_reg_392_pp0_iter1_reg = ap_const_lv1_1))) then 
            m_axi_gmem6_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem6_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    out_vec_1_fu_328_p2 <= (shl_ln285_1_fu_310_p2 or and_ln285_fu_322_p2);

    result_fifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, result_fifo_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            result_fifo_blk_n <= result_fifo_empty_n;
        else 
            result_fifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    result_fifo_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            result_fifo_read <= ap_const_logic_1;
        else 
            result_fifo_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln276_fu_196_p3 <= 
        ap_const_lv7_0 when (icmp_ln281_fu_190_p2(0) = '1') else 
        ap_sig_allocacmp_d_load;
    select_ln279_fu_210_p3 <= 
        add_ln279_1_fu_204_p2 when (icmp_ln281_fu_190_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
        sext_ln287_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln287_s_reg_382),64));

    shl_ln1_fu_290_p3 <= (trunc_ln285_reg_387_pp0_iter1_reg & ap_const_lv3_0);
    shl_ln285_1_fu_310_p2 <= std_logic_vector(shift_left(unsigned(zext_ln285_1_fu_307_p1),to_integer(unsigned('0' & zext_ln285_fu_297_p1(31-1 downto 0)))));
    shl_ln285_fu_301_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv512_lc_3),to_integer(unsigned('0' & zext_ln285_fu_297_p1(31-1 downto 0)))));
    shl_ln_fu_218_p3 <= (select_ln279_fu_210_p3 & ap_const_lv6_0);
    trunc_ln285_fu_246_p1 <= select_ln276_fu_196_p3(6 - 1 downto 0);
    trunc_ln287_fu_334_p1 <= out_vec_fu_110(504 - 1 downto 0);
    xor_ln285_fu_316_p2 <= (shl_ln285_fu_301_p2 xor ap_const_lv512_lc_4);
    zext_ln285_1_fu_307_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_fifo_read_reg_402),512));
    zext_ln285_fu_297_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln1_fu_290_p3),512));
    zext_ln287_fu_226_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_218_p3),64));
end behav;
