

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "13", "119", "121", "122", "123", "124", "125", "126"],
		"CDFG" : "spmm_stage",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "7", "Name" : "entry_proc_U0"},
			{"ID" : "8", "Name" : "spmm_load_csr_U0"},
			{"ID" : "13", "Name" : "spmm_compute_U0"}],
		"OutputProcess" : [
			{"ID" : "119", "Name" : "spmm_store_U0"}],
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "spmm_load_csr_U0", "Port" : "gmem0"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "spmm_load_csr_U0", "Port" : "gmem1"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "8", "SubInstance" : "spmm_load_csr_U0", "Port" : "gmem2"}]},
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "13", "SubInstance" : "spmm_compute_U0", "Port" : "gmem3"}]},
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "119", "SubInstance" : "spmm_store_U0", "Port" : "gmem4"}]},
			{"Name" : "row_length", "Type" : "None", "Direction" : "I"},
			{"Name" : "colind", "Type" : "None", "Direction" : "I"},
			{"Name" : "values", "Type" : "None", "Direction" : "I"},
			{"Name" : "H_temp", "Type" : "None", "Direction" : "I"},
			{"Name" : "nnz_total", "Type" : "None", "Direction" : "I"},
			{"Name" : "H_out", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem3_m_axi_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem4_m_axi_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "1",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "H_out", "Type" : "None", "Direction" : "I"},
			{"Name" : "H_out_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["119"], "DependentChan" : "121", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "H_out_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spmm_load_csr_U0", "Parent" : "0", "Child" : ["9", "11"],
		"CDFG" : "spmm_load_csr",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_ROWS_fu_115", "Port" : "gmem0", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "row_length", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124", "Port" : "gmem1", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "colind", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124", "Port" : "gmem2", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "values", "Type" : "None", "Direction" : "I"},
			{"Name" : "nnz_total", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["13"], "DependentChan" : "122", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "9", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_ROWS_fu_115", "Port" : "row_fifo", "Inst_start_state" : "10", "Inst_end_state" : "11"}]},
			{"Name" : "col_fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["13"], "DependentChan" : "123", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124", "Port" : "col_fifo", "Inst_start_state" : "12", "Inst_end_state" : "13"}]},
			{"Name" : "val_fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["13"], "DependentChan" : "124", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "11", "SubInstance" : "grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124", "Port" : "val_fifo", "Inst_start_state" : "12", "Inst_end_state" : "13"}]}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_load_csr_U0.grp_spmm_load_csr_Pipeline_LOAD_ROWS_fu_115", "Parent" : "8", "Child" : ["10"],
		"CDFG" : "spmm_load_csr_Pipeline_LOAD_ROWS",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2711", "EstimateLatencyMax" : "2711",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln17", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_fifo", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "row_fifo_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "LOAD_ROWS", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "10", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_load_csr_U0.grp_spmm_load_csr_Pipeline_LOAD_ROWS_fu_115.flow_control_loop_pipe_sequential_init_U", "Parent" : "9"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_load_csr_U0.grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124", "Parent" : "8", "Child" : ["12"],
		"CDFG" : "spmm_load_csr_Pipeline_LOAD_NNZ",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "nnz_total", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln23", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln23_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "col_fifo", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "col_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "val_fifo", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "val_fifo_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "LOAD_NNZ", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_load_csr_U0.grp_spmm_load_csr_Pipeline_LOAD_NNZ_fu_124.flow_control_loop_pipe_sequential_init_U", "Parent" : "11"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0", "Parent" : "0", "Child" : ["14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "80", "83", "85"],
		"CDFG" : "spmm_compute",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259969", "EstimateLatencyMax" : "10209161",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem3_blk_n_AR", "Type" : "RtlSignal"}],
				"SubConnect" : [
					{"ID" : "83", "SubInstance" : "grp_spmm_compute_Pipeline_SPMM_LOAD_H_fu_470", "Port" : "gmem3", "Inst_start_state" : "13", "Inst_end_state" : "14"}]},
			{"Name" : "H_temp", "Type" : "None", "Direction" : "I"},
			{"Name" : "row_fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["8"], "DependentChan" : "122", "DependentChanDepth" : "16", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "row_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "col_fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["8"], "DependentChan" : "123", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "col_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "val_fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["8"], "DependentChan" : "124", "DependentChanDepth" : "256", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "val_fifo_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "result_fifo", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["119"], "DependentChan" : "125", "DependentChanDepth" : "32", "DependentChanType" : "0",
				"SubConnect" : [
					{"ID" : "80", "SubInstance" : "grp_spmm_compute_Pipeline_SPMM_WRITE_fu_432", "Port" : "result_fifo", "Inst_start_state" : "4", "Inst_end_state" : "17"}]}],
		"Loop" : [
			{"Name" : "SPMM_NNZ", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state16"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state3"], "PostState" : ["ap_ST_fsm_state17"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "SPMM_ROW", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "17", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state17"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_U", "Parent" : "13"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_1_U", "Parent" : "13"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_2_U", "Parent" : "13"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_3_U", "Parent" : "13"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_4_U", "Parent" : "13"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_5_U", "Parent" : "13"},
	{"ID" : "20", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_6_U", "Parent" : "13"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_7_U", "Parent" : "13"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_8_U", "Parent" : "13"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_9_U", "Parent" : "13"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_10_U", "Parent" : "13"},
	{"ID" : "25", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_11_U", "Parent" : "13"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_12_U", "Parent" : "13"},
	{"ID" : "27", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_13_U", "Parent" : "13"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_14_U", "Parent" : "13"},
	{"ID" : "29", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_15_U", "Parent" : "13"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_16_U", "Parent" : "13"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_17_U", "Parent" : "13"},
	{"ID" : "32", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_18_U", "Parent" : "13"},
	{"ID" : "33", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_19_U", "Parent" : "13"},
	{"ID" : "34", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_20_U", "Parent" : "13"},
	{"ID" : "35", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_21_U", "Parent" : "13"},
	{"ID" : "36", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_22_U", "Parent" : "13"},
	{"ID" : "37", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_23_U", "Parent" : "13"},
	{"ID" : "38", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_24_U", "Parent" : "13"},
	{"ID" : "39", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_25_U", "Parent" : "13"},
	{"ID" : "40", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_26_U", "Parent" : "13"},
	{"ID" : "41", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_27_U", "Parent" : "13"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_28_U", "Parent" : "13"},
	{"ID" : "43", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_29_U", "Parent" : "13"},
	{"ID" : "44", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_30_U", "Parent" : "13"},
	{"ID" : "45", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.acc_31_U", "Parent" : "13"},
	{"ID" : "46", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_U", "Parent" : "13"},
	{"ID" : "47", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_1_U", "Parent" : "13"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_2_U", "Parent" : "13"},
	{"ID" : "49", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_3_U", "Parent" : "13"},
	{"ID" : "50", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_4_U", "Parent" : "13"},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_5_U", "Parent" : "13"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_6_U", "Parent" : "13"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_7_U", "Parent" : "13"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_8_U", "Parent" : "13"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_9_U", "Parent" : "13"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_10_U", "Parent" : "13"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_11_U", "Parent" : "13"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_12_U", "Parent" : "13"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_13_U", "Parent" : "13"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_14_U", "Parent" : "13"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_15_U", "Parent" : "13"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_16_U", "Parent" : "13"},
	{"ID" : "63", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_17_U", "Parent" : "13"},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_18_U", "Parent" : "13"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_19_U", "Parent" : "13"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_20_U", "Parent" : "13"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_21_U", "Parent" : "13"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_22_U", "Parent" : "13"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_23_U", "Parent" : "13"},
	{"ID" : "70", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_24_U", "Parent" : "13"},
	{"ID" : "71", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_25_U", "Parent" : "13"},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_26_U", "Parent" : "13"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_27_U", "Parent" : "13"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_28_U", "Parent" : "13"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_29_U", "Parent" : "13"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_30_U", "Parent" : "13"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.h_buf_31_U", "Parent" : "13"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_INIT_fu_396", "Parent" : "13", "Child" : ["79"],
		"CDFG" : "spmm_compute_Pipeline_SPMM_INIT",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "acc", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "SPMM_INIT", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_state1", "FirstStateIter" : "", "FirstStateBlock" : "ap_ST_fsm_state1_blk", "LastState" : "ap_ST_fsm_state1", "LastStateIter" : "", "LastStateBlock" : "ap_ST_fsm_state1_blk", "QuitState" : "ap_ST_fsm_state1", "QuitStateIter" : "", "QuitStateBlock" : "ap_ST_fsm_state1_blk", "OneDepthLoop" : "1", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_INIT_fu_396.flow_control_loop_pipe_sequential_init_U", "Parent" : "78"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_WRITE_fu_432", "Parent" : "13", "Child" : ["81", "82"],
		"CDFG" : "spmm_compute_Pipeline_SPMM_WRITE",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "acc_31", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "result_fifo", "Type" : "Fifo", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "result_fifo_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "SPMM_WRITE", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_WRITE_fu_432.sparsemux_65_5_26_1_1_U187", "Parent" : "80"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_WRITE_fu_432.flow_control_loop_pipe_sequential_init_U", "Parent" : "80"},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_LOAD_H_fu_470", "Parent" : "13", "Child" : ["84"],
		"CDFG" : "spmm_compute_Pipeline_SPMM_LOAD_H",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem3", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem3_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "sext_ln62_1", "Type" : "None", "Direction" : "I"},
			{"Name" : "h_buf_31", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_30", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_29", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_28", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_27", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_26", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_25", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_24", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_23", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_22", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_21", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_20", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_19", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_18", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_17", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_16", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_15", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_14", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_13", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_12", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_11", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_10", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_9", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_8", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "h_buf", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "SPMM_LOAD_H", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "84", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_LOAD_H_fu_470.flow_control_loop_pipe_sequential_init_U", "Parent" : "83"},
	{"ID" : "85", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509", "Parent" : "13", "Child" : ["86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118"],
		"CDFG" : "spmm_compute_Pipeline_SPMM_MAC",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "acc_31", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_30", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_29", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_28", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_27", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_26", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_25", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_24", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_23", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_22", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_21", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_20", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_19", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_18", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_17", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_16", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_15", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_14", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_13", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_12", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_11", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_10", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_9", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_8", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_7", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_6", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_5", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_4", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_3", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_2", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc_1", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "acc", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "h_buf", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "sext_ln72", "Type" : "None", "Direction" : "I"},
			{"Name" : "h_buf_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_8", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_9", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_10", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_11", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_12", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_13", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_14", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_15", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_16", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_17", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_18", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_19", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_20", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_21", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_22", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_23", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_24", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_25", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_26", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_27", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_28", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_29", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_30", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "h_buf_31", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "SPMM_MAC", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter0", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U89", "Parent" : "85"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U90", "Parent" : "85"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U91", "Parent" : "85"},
	{"ID" : "89", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U92", "Parent" : "85"},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U93", "Parent" : "85"},
	{"ID" : "91", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U94", "Parent" : "85"},
	{"ID" : "92", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U95", "Parent" : "85"},
	{"ID" : "93", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U96", "Parent" : "85"},
	{"ID" : "94", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U97", "Parent" : "85"},
	{"ID" : "95", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U98", "Parent" : "85"},
	{"ID" : "96", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U99", "Parent" : "85"},
	{"ID" : "97", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U100", "Parent" : "85"},
	{"ID" : "98", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U101", "Parent" : "85"},
	{"ID" : "99", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U102", "Parent" : "85"},
	{"ID" : "100", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U103", "Parent" : "85"},
	{"ID" : "101", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U104", "Parent" : "85"},
	{"ID" : "102", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U105", "Parent" : "85"},
	{"ID" : "103", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U106", "Parent" : "85"},
	{"ID" : "104", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U107", "Parent" : "85"},
	{"ID" : "105", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U108", "Parent" : "85"},
	{"ID" : "106", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U109", "Parent" : "85"},
	{"ID" : "107", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U110", "Parent" : "85"},
	{"ID" : "108", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U111", "Parent" : "85"},
	{"ID" : "109", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U112", "Parent" : "85"},
	{"ID" : "110", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U113", "Parent" : "85"},
	{"ID" : "111", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U114", "Parent" : "85"},
	{"ID" : "112", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U115", "Parent" : "85"},
	{"ID" : "113", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U116", "Parent" : "85"},
	{"ID" : "114", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U117", "Parent" : "85"},
	{"ID" : "115", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U118", "Parent" : "85"},
	{"ID" : "116", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U119", "Parent" : "85"},
	{"ID" : "117", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.mul_26s_26s_52_1_1_U120", "Parent" : "85"},
	{"ID" : "118", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.spmm_compute_U0.grp_spmm_compute_Pipeline_SPMM_MAC_fu_509.flow_control_loop_pipe_sequential_init_U", "Parent" : "85"},
	{"ID" : "119", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.spmm_store_U0", "Parent" : "0", "Child" : ["120"],
		"CDFG" : "spmm_store",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "173322", "EstimateLatencyMax" : "173322",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"StartSource" : "7",
		"StartFifo" : "start_for_spmm_store_U0_U",
		"Port" : [
			{"Name" : "gmem4", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem4_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem4_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem4_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "H_out", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "121", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "H_out_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "result_fifo", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["13"], "DependentChan" : "125", "DependentChanDepth" : "32", "DependentChanType" : "0",
				"BlockSignal" : [
					{"Name" : "result_fifo_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "SPMM_STORE_ROW_SPMM_STORE_FEAT", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter9", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter9", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "120", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.spmm_store_U0.flow_control_loop_delay_pipe_U", "Parent" : "119"},
	{"ID" : "121", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.H_out_c_U", "Parent" : "0"},
	{"ID" : "122", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.row_fifo_U", "Parent" : "0"},
	{"ID" : "123", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.col_fifo_U", "Parent" : "0"},
	{"ID" : "124", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.val_fifo_U", "Parent" : "0"},
	{"ID" : "125", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.result_fifo_U", "Parent" : "0"},
	{"ID" : "126", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_spmm_store_U0_U", "Parent" : "0"}]}
