# Inferred from syn.compile.pipeline_loops=64
set_directive_pipeline gemm_write/VITIS_LOOP_155_3
set_directive_pipeline gemm_compute/COMP_EMIT
set_directive_pipeline gemm_read_w/VITIS_LOOP_56_4
set_directive_pipeline gemm_read_x/VITIS_LOOP_36_4
# Inferred from Performance Budgeter performance directives
set_directive_loop_flatten gemm_read_x/VITIS_LOOP_35_3
set_directive_loop_flatten gemm_read_x/VITIS_LOOP_33_1
set_directive_loop_flatten gemm_read_w/VITIS_LOOP_55_3
set_directive_loop_flatten gemm_read_w/VITIS_LOOP_53_1
set_directive_loop_flatten gemm_write/VITIS_LOOP_153_1
