// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module integrated_gcn_spmm_compute_Pipeline_SPMM_INIT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        acc_31_address0,
        acc_31_ce0,
        acc_31_we0,
        acc_31_d0,
        acc_30_address0,
        acc_30_ce0,
        acc_30_we0,
        acc_30_d0,
        acc_29_address0,
        acc_29_ce0,
        acc_29_we0,
        acc_29_d0,
        acc_28_address0,
        acc_28_ce0,
        acc_28_we0,
        acc_28_d0,
        acc_27_address0,
        acc_27_ce0,
        acc_27_we0,
        acc_27_d0,
        acc_26_address0,
        acc_26_ce0,
        acc_26_we0,
        acc_26_d0,
        acc_25_address0,
        acc_25_ce0,
        acc_25_we0,
        acc_25_d0,
        acc_24_address0,
        acc_24_ce0,
        acc_24_we0,
        acc_24_d0,
        acc_23_address0,
        acc_23_ce0,
        acc_23_we0,
        acc_23_d0,
        acc_22_address0,
        acc_22_ce0,
        acc_22_we0,
        acc_22_d0,
        acc_21_address0,
        acc_21_ce0,
        acc_21_we0,
        acc_21_d0,
        acc_20_address0,
        acc_20_ce0,
        acc_20_we0,
        acc_20_d0,
        acc_19_address0,
        acc_19_ce0,
        acc_19_we0,
        acc_19_d0,
        acc_18_address0,
        acc_18_ce0,
        acc_18_we0,
        acc_18_d0,
        acc_17_address0,
        acc_17_ce0,
        acc_17_we0,
        acc_17_d0,
        acc_16_address0,
        acc_16_ce0,
        acc_16_we0,
        acc_16_d0,
        acc_15_address0,
        acc_15_ce0,
        acc_15_we0,
        acc_15_d0,
        acc_14_address0,
        acc_14_ce0,
        acc_14_we0,
        acc_14_d0,
        acc_13_address0,
        acc_13_ce0,
        acc_13_we0,
        acc_13_d0,
        acc_12_address0,
        acc_12_ce0,
        acc_12_we0,
        acc_12_d0,
        acc_11_address0,
        acc_11_ce0,
        acc_11_we0,
        acc_11_d0,
        acc_10_address0,
        acc_10_ce0,
        acc_10_we0,
        acc_10_d0,
        acc_9_address0,
        acc_9_ce0,
        acc_9_we0,
        acc_9_d0,
        acc_8_address0,
        acc_8_ce0,
        acc_8_we0,
        acc_8_d0,
        acc_7_address0,
        acc_7_ce0,
        acc_7_we0,
        acc_7_d0,
        acc_6_address0,
        acc_6_ce0,
        acc_6_we0,
        acc_6_d0,
        acc_5_address0,
        acc_5_ce0,
        acc_5_we0,
        acc_5_d0,
        acc_4_address0,
        acc_4_ce0,
        acc_4_we0,
        acc_4_d0,
        acc_3_address0,
        acc_3_ce0,
        acc_3_we0,
        acc_3_d0,
        acc_2_address0,
        acc_2_ce0,
        acc_2_we0,
        acc_2_d0,
        acc_1_address0,
        acc_1_ce0,
        acc_1_we0,
        acc_1_d0,
        acc_address0,
        acc_ce0,
        acc_we0,
        acc_d0
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [0:0] acc_31_address0;
output   acc_31_ce0;
output   acc_31_we0;
output  [31:0] acc_31_d0;
output  [0:0] acc_30_address0;
output   acc_30_ce0;
output   acc_30_we0;
output  [31:0] acc_30_d0;
output  [0:0] acc_29_address0;
output   acc_29_ce0;
output   acc_29_we0;
output  [31:0] acc_29_d0;
output  [0:0] acc_28_address0;
output   acc_28_ce0;
output   acc_28_we0;
output  [31:0] acc_28_d0;
output  [0:0] acc_27_address0;
output   acc_27_ce0;
output   acc_27_we0;
output  [31:0] acc_27_d0;
output  [0:0] acc_26_address0;
output   acc_26_ce0;
output   acc_26_we0;
output  [31:0] acc_26_d0;
output  [0:0] acc_25_address0;
output   acc_25_ce0;
output   acc_25_we0;
output  [31:0] acc_25_d0;
output  [0:0] acc_24_address0;
output   acc_24_ce0;
output   acc_24_we0;
output  [31:0] acc_24_d0;
output  [0:0] acc_23_address0;
output   acc_23_ce0;
output   acc_23_we0;
output  [31:0] acc_23_d0;
output  [0:0] acc_22_address0;
output   acc_22_ce0;
output   acc_22_we0;
output  [31:0] acc_22_d0;
output  [0:0] acc_21_address0;
output   acc_21_ce0;
output   acc_21_we0;
output  [31:0] acc_21_d0;
output  [0:0] acc_20_address0;
output   acc_20_ce0;
output   acc_20_we0;
output  [31:0] acc_20_d0;
output  [0:0] acc_19_address0;
output   acc_19_ce0;
output   acc_19_we0;
output  [31:0] acc_19_d0;
output  [0:0] acc_18_address0;
output   acc_18_ce0;
output   acc_18_we0;
output  [31:0] acc_18_d0;
output  [0:0] acc_17_address0;
output   acc_17_ce0;
output   acc_17_we0;
output  [31:0] acc_17_d0;
output  [0:0] acc_16_address0;
output   acc_16_ce0;
output   acc_16_we0;
output  [31:0] acc_16_d0;
output  [0:0] acc_15_address0;
output   acc_15_ce0;
output   acc_15_we0;
output  [31:0] acc_15_d0;
output  [0:0] acc_14_address0;
output   acc_14_ce0;
output   acc_14_we0;
output  [31:0] acc_14_d0;
output  [0:0] acc_13_address0;
output   acc_13_ce0;
output   acc_13_we0;
output  [31:0] acc_13_d0;
output  [0:0] acc_12_address0;
output   acc_12_ce0;
output   acc_12_we0;
output  [31:0] acc_12_d0;
output  [0:0] acc_11_address0;
output   acc_11_ce0;
output   acc_11_we0;
output  [31:0] acc_11_d0;
output  [0:0] acc_10_address0;
output   acc_10_ce0;
output   acc_10_we0;
output  [31:0] acc_10_d0;
output  [0:0] acc_9_address0;
output   acc_9_ce0;
output   acc_9_we0;
output  [31:0] acc_9_d0;
output  [0:0] acc_8_address0;
output   acc_8_ce0;
output   acc_8_we0;
output  [31:0] acc_8_d0;
output  [0:0] acc_7_address0;
output   acc_7_ce0;
output   acc_7_we0;
output  [31:0] acc_7_d0;
output  [0:0] acc_6_address0;
output   acc_6_ce0;
output   acc_6_we0;
output  [31:0] acc_6_d0;
output  [0:0] acc_5_address0;
output   acc_5_ce0;
output   acc_5_we0;
output  [31:0] acc_5_d0;
output  [0:0] acc_4_address0;
output   acc_4_ce0;
output   acc_4_we0;
output  [31:0] acc_4_d0;
output  [0:0] acc_3_address0;
output   acc_3_ce0;
output   acc_3_we0;
output  [31:0] acc_3_d0;
output  [0:0] acc_2_address0;
output   acc_2_ce0;
output   acc_2_we0;
output  [31:0] acc_2_d0;
output  [0:0] acc_1_address0;
output   acc_1_ce0;
output   acc_1_we0;
output  [31:0] acc_1_d0;
output  [0:0] acc_address0;
output   acc_ce0;
output   acc_we0;
output  [31:0] acc_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_fu_554_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln241_fu_570_p1;
reg   [6:0] f_fu_94;
wire   [6:0] add_ln241_fu_606_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_f_4;
reg    acc_we0_local;
reg    acc_ce0_local;
reg    acc_1_we0_local;
reg    acc_1_ce0_local;
reg    acc_2_we0_local;
reg    acc_2_ce0_local;
reg    acc_3_we0_local;
reg    acc_3_ce0_local;
reg    acc_4_we0_local;
reg    acc_4_ce0_local;
reg    acc_5_we0_local;
reg    acc_5_ce0_local;
reg    acc_6_we0_local;
reg    acc_6_ce0_local;
reg    acc_7_we0_local;
reg    acc_7_ce0_local;
reg    acc_8_we0_local;
reg    acc_8_ce0_local;
reg    acc_9_we0_local;
reg    acc_9_ce0_local;
reg    acc_10_we0_local;
reg    acc_10_ce0_local;
reg    acc_11_we0_local;
reg    acc_11_ce0_local;
reg    acc_12_we0_local;
reg    acc_12_ce0_local;
reg    acc_13_we0_local;
reg    acc_13_ce0_local;
reg    acc_14_we0_local;
reg    acc_14_ce0_local;
reg    acc_15_we0_local;
reg    acc_15_ce0_local;
reg    acc_16_we0_local;
reg    acc_16_ce0_local;
reg    acc_17_we0_local;
reg    acc_17_ce0_local;
reg    acc_18_we0_local;
reg    acc_18_ce0_local;
reg    acc_19_we0_local;
reg    acc_19_ce0_local;
reg    acc_20_we0_local;
reg    acc_20_ce0_local;
reg    acc_21_we0_local;
reg    acc_21_ce0_local;
reg    acc_22_we0_local;
reg    acc_22_ce0_local;
reg    acc_23_we0_local;
reg    acc_23_ce0_local;
reg    acc_24_we0_local;
reg    acc_24_ce0_local;
reg    acc_25_we0_local;
reg    acc_25_ce0_local;
reg    acc_26_we0_local;
reg    acc_26_ce0_local;
reg    acc_27_we0_local;
reg    acc_27_ce0_local;
reg    acc_28_we0_local;
reg    acc_28_ce0_local;
reg    acc_29_we0_local;
reg    acc_29_ce0_local;
reg    acc_30_we0_local;
reg    acc_30_ce0_local;
reg    acc_31_we0_local;
reg    acc_31_ce0_local;
wire   [0:0] tmp_7_fu_562_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 f_fu_94 = 7'd0;
#0 ap_done_reg = 1'b0;
end

integrated_gcn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((tmp_fu_554_p3 == 1'd0)) begin
            f_fu_94 <= add_ln241_fu_606_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            f_fu_94 <= 7'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_10_ce0_local = 1'b1;
    end else begin
        acc_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_10_we0_local = 1'b1;
    end else begin
        acc_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_11_ce0_local = 1'b1;
    end else begin
        acc_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_11_we0_local = 1'b1;
    end else begin
        acc_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_12_ce0_local = 1'b1;
    end else begin
        acc_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_12_we0_local = 1'b1;
    end else begin
        acc_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_13_ce0_local = 1'b1;
    end else begin
        acc_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_13_we0_local = 1'b1;
    end else begin
        acc_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_14_ce0_local = 1'b1;
    end else begin
        acc_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_14_we0_local = 1'b1;
    end else begin
        acc_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_15_ce0_local = 1'b1;
    end else begin
        acc_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_15_we0_local = 1'b1;
    end else begin
        acc_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_16_ce0_local = 1'b1;
    end else begin
        acc_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_16_we0_local = 1'b1;
    end else begin
        acc_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_17_ce0_local = 1'b1;
    end else begin
        acc_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_17_we0_local = 1'b1;
    end else begin
        acc_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_18_ce0_local = 1'b1;
    end else begin
        acc_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_18_we0_local = 1'b1;
    end else begin
        acc_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_19_ce0_local = 1'b1;
    end else begin
        acc_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_19_we0_local = 1'b1;
    end else begin
        acc_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_ce0_local = 1'b1;
    end else begin
        acc_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_1_we0_local = 1'b1;
    end else begin
        acc_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_20_ce0_local = 1'b1;
    end else begin
        acc_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_20_we0_local = 1'b1;
    end else begin
        acc_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_21_ce0_local = 1'b1;
    end else begin
        acc_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_21_we0_local = 1'b1;
    end else begin
        acc_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_22_ce0_local = 1'b1;
    end else begin
        acc_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_22_we0_local = 1'b1;
    end else begin
        acc_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_23_ce0_local = 1'b1;
    end else begin
        acc_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_23_we0_local = 1'b1;
    end else begin
        acc_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_24_ce0_local = 1'b1;
    end else begin
        acc_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_24_we0_local = 1'b1;
    end else begin
        acc_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_25_ce0_local = 1'b1;
    end else begin
        acc_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_25_we0_local = 1'b1;
    end else begin
        acc_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_26_ce0_local = 1'b1;
    end else begin
        acc_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_26_we0_local = 1'b1;
    end else begin
        acc_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_27_ce0_local = 1'b1;
    end else begin
        acc_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_27_we0_local = 1'b1;
    end else begin
        acc_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_28_ce0_local = 1'b1;
    end else begin
        acc_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_28_we0_local = 1'b1;
    end else begin
        acc_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_29_ce0_local = 1'b1;
    end else begin
        acc_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_29_we0_local = 1'b1;
    end else begin
        acc_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_ce0_local = 1'b1;
    end else begin
        acc_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_2_we0_local = 1'b1;
    end else begin
        acc_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_30_ce0_local = 1'b1;
    end else begin
        acc_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_30_we0_local = 1'b1;
    end else begin
        acc_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_31_ce0_local = 1'b1;
    end else begin
        acc_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_31_we0_local = 1'b1;
    end else begin
        acc_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_ce0_local = 1'b1;
    end else begin
        acc_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_3_we0_local = 1'b1;
    end else begin
        acc_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_ce0_local = 1'b1;
    end else begin
        acc_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_4_we0_local = 1'b1;
    end else begin
        acc_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_ce0_local = 1'b1;
    end else begin
        acc_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_5_we0_local = 1'b1;
    end else begin
        acc_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_ce0_local = 1'b1;
    end else begin
        acc_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_6_we0_local = 1'b1;
    end else begin
        acc_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_ce0_local = 1'b1;
    end else begin
        acc_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_7_we0_local = 1'b1;
    end else begin
        acc_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_8_ce0_local = 1'b1;
    end else begin
        acc_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_8_we0_local = 1'b1;
    end else begin
        acc_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_9_ce0_local = 1'b1;
    end else begin
        acc_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_9_we0_local = 1'b1;
    end else begin
        acc_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_ce0_local = 1'b1;
    end else begin
        acc_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd0) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_we0_local = 1'b1;
    end else begin
        acc_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_554_p3 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_f_4 = 7'd0;
    end else begin
        ap_sig_allocacmp_f_4 = f_fu_94;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_address0 = zext_ln241_fu_570_p1;

assign acc_10_ce0 = acc_10_ce0_local;

assign acc_10_d0 = 32'd0;

assign acc_10_we0 = acc_10_we0_local;

assign acc_11_address0 = zext_ln241_fu_570_p1;

assign acc_11_ce0 = acc_11_ce0_local;

assign acc_11_d0 = 32'd0;

assign acc_11_we0 = acc_11_we0_local;

assign acc_12_address0 = zext_ln241_fu_570_p1;

assign acc_12_ce0 = acc_12_ce0_local;

assign acc_12_d0 = 32'd0;

assign acc_12_we0 = acc_12_we0_local;

assign acc_13_address0 = zext_ln241_fu_570_p1;

assign acc_13_ce0 = acc_13_ce0_local;

assign acc_13_d0 = 32'd0;

assign acc_13_we0 = acc_13_we0_local;

assign acc_14_address0 = zext_ln241_fu_570_p1;

assign acc_14_ce0 = acc_14_ce0_local;

assign acc_14_d0 = 32'd0;

assign acc_14_we0 = acc_14_we0_local;

assign acc_15_address0 = zext_ln241_fu_570_p1;

assign acc_15_ce0 = acc_15_ce0_local;

assign acc_15_d0 = 32'd0;

assign acc_15_we0 = acc_15_we0_local;

assign acc_16_address0 = zext_ln241_fu_570_p1;

assign acc_16_ce0 = acc_16_ce0_local;

assign acc_16_d0 = 32'd0;

assign acc_16_we0 = acc_16_we0_local;

assign acc_17_address0 = zext_ln241_fu_570_p1;

assign acc_17_ce0 = acc_17_ce0_local;

assign acc_17_d0 = 32'd0;

assign acc_17_we0 = acc_17_we0_local;

assign acc_18_address0 = zext_ln241_fu_570_p1;

assign acc_18_ce0 = acc_18_ce0_local;

assign acc_18_d0 = 32'd0;

assign acc_18_we0 = acc_18_we0_local;

assign acc_19_address0 = zext_ln241_fu_570_p1;

assign acc_19_ce0 = acc_19_ce0_local;

assign acc_19_d0 = 32'd0;

assign acc_19_we0 = acc_19_we0_local;

assign acc_1_address0 = zext_ln241_fu_570_p1;

assign acc_1_ce0 = acc_1_ce0_local;

assign acc_1_d0 = 32'd0;

assign acc_1_we0 = acc_1_we0_local;

assign acc_20_address0 = zext_ln241_fu_570_p1;

assign acc_20_ce0 = acc_20_ce0_local;

assign acc_20_d0 = 32'd0;

assign acc_20_we0 = acc_20_we0_local;

assign acc_21_address0 = zext_ln241_fu_570_p1;

assign acc_21_ce0 = acc_21_ce0_local;

assign acc_21_d0 = 32'd0;

assign acc_21_we0 = acc_21_we0_local;

assign acc_22_address0 = zext_ln241_fu_570_p1;

assign acc_22_ce0 = acc_22_ce0_local;

assign acc_22_d0 = 32'd0;

assign acc_22_we0 = acc_22_we0_local;

assign acc_23_address0 = zext_ln241_fu_570_p1;

assign acc_23_ce0 = acc_23_ce0_local;

assign acc_23_d0 = 32'd0;

assign acc_23_we0 = acc_23_we0_local;

assign acc_24_address0 = zext_ln241_fu_570_p1;

assign acc_24_ce0 = acc_24_ce0_local;

assign acc_24_d0 = 32'd0;

assign acc_24_we0 = acc_24_we0_local;

assign acc_25_address0 = zext_ln241_fu_570_p1;

assign acc_25_ce0 = acc_25_ce0_local;

assign acc_25_d0 = 32'd0;

assign acc_25_we0 = acc_25_we0_local;

assign acc_26_address0 = zext_ln241_fu_570_p1;

assign acc_26_ce0 = acc_26_ce0_local;

assign acc_26_d0 = 32'd0;

assign acc_26_we0 = acc_26_we0_local;

assign acc_27_address0 = zext_ln241_fu_570_p1;

assign acc_27_ce0 = acc_27_ce0_local;

assign acc_27_d0 = 32'd0;

assign acc_27_we0 = acc_27_we0_local;

assign acc_28_address0 = zext_ln241_fu_570_p1;

assign acc_28_ce0 = acc_28_ce0_local;

assign acc_28_d0 = 32'd0;

assign acc_28_we0 = acc_28_we0_local;

assign acc_29_address0 = zext_ln241_fu_570_p1;

assign acc_29_ce0 = acc_29_ce0_local;

assign acc_29_d0 = 32'd0;

assign acc_29_we0 = acc_29_we0_local;

assign acc_2_address0 = zext_ln241_fu_570_p1;

assign acc_2_ce0 = acc_2_ce0_local;

assign acc_2_d0 = 32'd0;

assign acc_2_we0 = acc_2_we0_local;

assign acc_30_address0 = zext_ln241_fu_570_p1;

assign acc_30_ce0 = acc_30_ce0_local;

assign acc_30_d0 = 32'd0;

assign acc_30_we0 = acc_30_we0_local;

assign acc_31_address0 = zext_ln241_fu_570_p1;

assign acc_31_ce0 = acc_31_ce0_local;

assign acc_31_d0 = 32'd0;

assign acc_31_we0 = acc_31_we0_local;

assign acc_3_address0 = zext_ln241_fu_570_p1;

assign acc_3_ce0 = acc_3_ce0_local;

assign acc_3_d0 = 32'd0;

assign acc_3_we0 = acc_3_we0_local;

assign acc_4_address0 = zext_ln241_fu_570_p1;

assign acc_4_ce0 = acc_4_ce0_local;

assign acc_4_d0 = 32'd0;

assign acc_4_we0 = acc_4_we0_local;

assign acc_5_address0 = zext_ln241_fu_570_p1;

assign acc_5_ce0 = acc_5_ce0_local;

assign acc_5_d0 = 32'd0;

assign acc_5_we0 = acc_5_we0_local;

assign acc_6_address0 = zext_ln241_fu_570_p1;

assign acc_6_ce0 = acc_6_ce0_local;

assign acc_6_d0 = 32'd0;

assign acc_6_we0 = acc_6_we0_local;

assign acc_7_address0 = zext_ln241_fu_570_p1;

assign acc_7_ce0 = acc_7_ce0_local;

assign acc_7_d0 = 32'd0;

assign acc_7_we0 = acc_7_we0_local;

assign acc_8_address0 = zext_ln241_fu_570_p1;

assign acc_8_ce0 = acc_8_ce0_local;

assign acc_8_d0 = 32'd0;

assign acc_8_we0 = acc_8_we0_local;

assign acc_9_address0 = zext_ln241_fu_570_p1;

assign acc_9_ce0 = acc_9_ce0_local;

assign acc_9_d0 = 32'd0;

assign acc_9_we0 = acc_9_we0_local;

assign acc_address0 = zext_ln241_fu_570_p1;

assign acc_ce0 = acc_ce0_local;

assign acc_d0 = 32'd0;

assign acc_we0 = acc_we0_local;

assign add_ln241_fu_606_p2 = (ap_sig_allocacmp_f_4 + 7'd32);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign tmp_7_fu_562_p3 = ap_sig_allocacmp_f_4[32'd5];

assign tmp_fu_554_p3 = ap_sig_allocacmp_f_4[32'd6];

assign zext_ln241_fu_570_p1 = tmp_7_fu_562_p3;

endmodule //integrated_gcn_spmm_compute_Pipeline_SPMM_INIT
