-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gemm_stage is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM0_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM0_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_DATA_WIDTH : INTEGER := 512;
    C_M_AXI_GMEM0_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM1_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_DATA_WIDTH : INTEGER := 512;
    C_M_AXI_GMEM1_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM1_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM2_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_DATA_WIDTH : INTEGER := 512;
    C_M_AXI_GMEM2_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM2_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM0_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM0_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM1_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM1_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_GMEM2_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM2_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM2_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_WUSER_WIDTH-1 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ADDR_WIDTH-1 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_DATA_WIDTH-1 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_RUSER_WIDTH-1 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_ID_WIDTH-1 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM0_BUSER_WIDTH-1 downto 0);
    m_axi_gmem1_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem1_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_WREADY : IN STD_LOGIC;
    m_axi_gmem1_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem1_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_WUSER_WIDTH-1 downto 0);
    m_axi_gmem1_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ADDR_WIDTH-1 downto 0);
    m_axi_gmem1_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem1_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RVALID : IN STD_LOGIC;
    m_axi_gmem1_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_DATA_WIDTH-1 downto 0);
    m_axi_gmem1_RLAST : IN STD_LOGIC;
    m_axi_gmem1_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_RUSER_WIDTH-1 downto 0);
    m_axi_gmem1_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BVALID : IN STD_LOGIC;
    m_axi_gmem1_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_ID_WIDTH-1 downto 0);
    m_axi_gmem1_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM1_BUSER_WIDTH-1 downto 0);
    m_axi_gmem2_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ADDR_WIDTH-1 downto 0);
    m_axi_gmem2_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ID_WIDTH-1 downto 0);
    m_axi_gmem2_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem2_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_WREADY : IN STD_LOGIC;
    m_axi_gmem2_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_DATA_WIDTH-1 downto 0);
    m_axi_gmem2_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem2_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ID_WIDTH-1 downto 0);
    m_axi_gmem2_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_WUSER_WIDTH-1 downto 0);
    m_axi_gmem2_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ADDR_WIDTH-1 downto 0);
    m_axi_gmem2_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ID_WIDTH-1 downto 0);
    m_axi_gmem2_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem2_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem2_RVALID : IN STD_LOGIC;
    m_axi_gmem2_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM2_DATA_WIDTH-1 downto 0);
    m_axi_gmem2_RLAST : IN STD_LOGIC;
    m_axi_gmem2_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ID_WIDTH-1 downto 0);
    m_axi_gmem2_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM2_RUSER_WIDTH-1 downto 0);
    m_axi_gmem2_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BVALID : IN STD_LOGIC;
    m_axi_gmem2_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM2_ID_WIDTH-1 downto 0);
    m_axi_gmem2_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM2_BUSER_WIDTH-1 downto 0);
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of gemm_stage is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "gemm_stage_gemm_stage,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=1782919,HLS_SYN_TPT=1782911,HLS_SYN_MEM=145,HLS_SYN_DSP=0,HLS_SYN_FF=38643,HLS_SYN_LUT=36826,HLS_VERSION=2025_2}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal X : STD_LOGIC_VECTOR (63 downto 0);
    signal W : STD_LOGIC_VECTOR (63 downto 0);
    signal H_temp : STD_LOGIC_VECTOR (63 downto 0);
    signal gmem0_0_AWREADY : STD_LOGIC;
    signal gmem0_0_WREADY : STD_LOGIC;
    signal gmem0_0_ARREADY : STD_LOGIC;
    signal gmem0_0_RVALID : STD_LOGIC;
    signal gmem0_0_RDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gmem0_0_RLAST : STD_LOGIC;
    signal gmem0_0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem0_0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem0_0_BVALID : STD_LOGIC;
    signal gmem1_0_AWREADY : STD_LOGIC;
    signal gmem1_0_WREADY : STD_LOGIC;
    signal gmem1_0_ARREADY : STD_LOGIC;
    signal gmem1_0_RVALID : STD_LOGIC;
    signal gmem1_0_RDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gmem1_0_RLAST : STD_LOGIC;
    signal gmem1_0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem1_0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem1_0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem1_0_BVALID : STD_LOGIC;
    signal gmem2_0_AWREADY : STD_LOGIC;
    signal gmem2_0_WREADY : STD_LOGIC;
    signal gmem2_0_ARREADY : STD_LOGIC;
    signal gmem2_0_RVALID : STD_LOGIC;
    signal gmem2_0_RDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gmem2_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem2_0_BVALID : STD_LOGIC;
    signal gmem2_0_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal gmem2_0_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem2_0_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_H_temp_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_H_temp_c_write : STD_LOGIC;
    signal gemm_read_X_U0_ap_start : STD_LOGIC;
    signal gemm_read_X_U0_ap_done : STD_LOGIC;
    signal gemm_read_X_U0_ap_continue : STD_LOGIC;
    signal gemm_read_X_U0_ap_idle : STD_LOGIC;
    signal gemm_read_X_U0_ap_ready : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal gemm_read_X_U0_X_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_X_U0_X_stream_write : STD_LOGIC;
    signal gemm_read_X_U0_start_out : STD_LOGIC;
    signal gemm_read_X_U0_start_write : STD_LOGIC;
    signal gemm_read_W_U0_ap_start : STD_LOGIC;
    signal gemm_read_W_U0_ap_done : STD_LOGIC;
    signal gemm_read_W_U0_ap_continue : STD_LOGIC;
    signal gemm_read_W_U0_ap_idle : STD_LOGIC;
    signal gemm_read_W_U0_ap_ready : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_AWVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WLAST : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_RREADY : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_BREADY : STD_LOGIC;
    signal gemm_read_W_U0_W_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_W_U0_W_stream_write : STD_LOGIC;
    signal gemm_compute_U0_ap_start : STD_LOGIC;
    signal gemm_compute_U0_ap_done : STD_LOGIC;
    signal gemm_compute_U0_ap_continue : STD_LOGIC;
    signal gemm_compute_U0_ap_idle : STD_LOGIC;
    signal gemm_compute_U0_ap_ready : STD_LOGIC;
    signal gemm_compute_U0_X_stream_read : STD_LOGIC;
    signal gemm_compute_U0_W_stream_read : STD_LOGIC;
    signal gemm_compute_U0_XW_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_compute_U0_XW_stream_write : STD_LOGIC;
    signal gemm_compute_U0_XW_stream_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_compute_U0_XW_stream_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_ap_start : STD_LOGIC;
    signal gemm_write_U0_ap_done : STD_LOGIC;
    signal gemm_write_U0_ap_continue : STD_LOGIC;
    signal gemm_write_U0_ap_idle : STD_LOGIC;
    signal gemm_write_U0_ap_ready : STD_LOGIC;
    signal gemm_write_U0_H_temp_read : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_AWVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WLAST : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_RREADY : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_BREADY : STD_LOGIC;
    signal gemm_write_U0_XW_stream_read : STD_LOGIC;
    signal H_temp_c_full_n : STD_LOGIC;
    signal H_temp_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal H_temp_c_empty_n : STD_LOGIC;
    signal H_temp_c_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal H_temp_c_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal X_stream_full_n : STD_LOGIC;
    signal X_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal X_stream_empty_n : STD_LOGIC;
    signal X_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal X_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal W_stream_full_n : STD_LOGIC;
    signal W_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal W_stream_empty_n : STD_LOGIC;
    signal W_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal W_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal XW_stream_full_n : STD_LOGIC;
    signal XW_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal XW_stream_empty_n : STD_LOGIC;
    signal XW_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal XW_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_gemm_read_X_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_gemm_read_X_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_gemm_read_W_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_gemm_read_W_U0_ap_ready : STD_LOGIC;
    signal start_for_gemm_write_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_write_U0_full_n : STD_LOGIC;
    signal start_for_gemm_write_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_write_U0_empty_n : STD_LOGIC;
    signal start_for_gemm_compute_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_compute_U0_full_n : STD_LOGIC;
    signal start_for_gemm_compute_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_compute_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gemm_stage_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        H_temp : IN STD_LOGIC_VECTOR (63 downto 0);
        H_temp_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        H_temp_c_full_n : IN STD_LOGIC;
        H_temp_c_write : OUT STD_LOGIC;
        H_temp_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        H_temp_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component gemm_stage_gemm_read_X IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        X_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        X_stream_full_n : IN STD_LOGIC;
        X_stream_write : OUT STD_LOGIC;
        X_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        X_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        X : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component gemm_stage_gemm_read_W IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_WREADY : IN STD_LOGIC;
        m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RVALID : IN STD_LOGIC;
        m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem1_0_RLAST : IN STD_LOGIC;
        m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BVALID : IN STD_LOGIC;
        m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        W_stream_full_n : IN STD_LOGIC;
        W_stream_write : OUT STD_LOGIC;
        W_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        W : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component gemm_stage_gemm_compute IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        X_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        X_stream_empty_n : IN STD_LOGIC;
        X_stream_read : OUT STD_LOGIC;
        X_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        X_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        W_stream_empty_n : IN STD_LOGIC;
        W_stream_read : OUT STD_LOGIC;
        W_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        XW_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        XW_stream_full_n : IN STD_LOGIC;
        XW_stream_write : OUT STD_LOGIC;
        XW_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        XW_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component gemm_stage_gemm_write IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        H_temp_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        H_temp_empty_n : IN STD_LOGIC;
        H_temp_read : OUT STD_LOGIC;
        H_temp_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        H_temp_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_WREADY : IN STD_LOGIC;
        m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RVALID : IN STD_LOGIC;
        m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem2_0_RLAST : IN STD_LOGIC;
        m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BVALID : IN STD_LOGIC;
        m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        XW_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        XW_stream_empty_n : IN STD_LOGIC;
        XW_stream_read : OUT STD_LOGIC;
        XW_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        XW_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component gemm_stage_fifo_w64_d4_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component gemm_stage_fifo_w512_d16_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (511 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (511 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component gemm_stage_start_for_gemm_write_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gemm_stage_start_for_gemm_compute_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component gemm_stage_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        X : OUT STD_LOGIC_VECTOR (63 downto 0);
        W : OUT STD_LOGIC_VECTOR (63 downto 0);
        H_temp : OUT STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component gemm_stage_gmem0_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component gemm_stage_gmem1_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component gemm_stage_gmem2_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component gemm_stage_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        X => X,
        W => W,
        H_temp => H_temp);

    gmem0_m_axi_U : component gemm_stage_gmem0_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM0_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM0_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM0_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM0_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM0_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM0_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM0_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM0_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM0_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM0_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM0_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 512,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem0_AWVALID,
        AWREADY => m_axi_gmem0_AWREADY,
        AWADDR => m_axi_gmem0_AWADDR,
        AWID => m_axi_gmem0_AWID,
        AWLEN => m_axi_gmem0_AWLEN,
        AWSIZE => m_axi_gmem0_AWSIZE,
        AWBURST => m_axi_gmem0_AWBURST,
        AWLOCK => m_axi_gmem0_AWLOCK,
        AWCACHE => m_axi_gmem0_AWCACHE,
        AWPROT => m_axi_gmem0_AWPROT,
        AWQOS => m_axi_gmem0_AWQOS,
        AWREGION => m_axi_gmem0_AWREGION,
        AWUSER => m_axi_gmem0_AWUSER,
        WVALID => m_axi_gmem0_WVALID,
        WREADY => m_axi_gmem0_WREADY,
        WDATA => m_axi_gmem0_WDATA,
        WSTRB => m_axi_gmem0_WSTRB,
        WLAST => m_axi_gmem0_WLAST,
        WID => m_axi_gmem0_WID,
        WUSER => m_axi_gmem0_WUSER,
        ARVALID => m_axi_gmem0_ARVALID,
        ARREADY => m_axi_gmem0_ARREADY,
        ARADDR => m_axi_gmem0_ARADDR,
        ARID => m_axi_gmem0_ARID,
        ARLEN => m_axi_gmem0_ARLEN,
        ARSIZE => m_axi_gmem0_ARSIZE,
        ARBURST => m_axi_gmem0_ARBURST,
        ARLOCK => m_axi_gmem0_ARLOCK,
        ARCACHE => m_axi_gmem0_ARCACHE,
        ARPROT => m_axi_gmem0_ARPROT,
        ARQOS => m_axi_gmem0_ARQOS,
        ARREGION => m_axi_gmem0_ARREGION,
        ARUSER => m_axi_gmem0_ARUSER,
        RVALID => m_axi_gmem0_RVALID,
        RREADY => m_axi_gmem0_RREADY,
        RDATA => m_axi_gmem0_RDATA,
        RLAST => m_axi_gmem0_RLAST,
        RID => m_axi_gmem0_RID,
        RUSER => m_axi_gmem0_RUSER,
        RRESP => m_axi_gmem0_RRESP,
        BVALID => m_axi_gmem0_BVALID,
        BREADY => m_axi_gmem0_BREADY,
        BRESP => m_axi_gmem0_BRESP,
        BID => m_axi_gmem0_BID,
        BUSER => m_axi_gmem0_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gemm_read_X_U0_m_axi_gmem0_0_ARVALID,
        I_CH0_ARREADY => gmem0_0_ARREADY,
        I_CH0_ARADDR => gemm_read_X_U0_m_axi_gmem0_0_ARADDR,
        I_CH0_ARLEN => gemm_read_X_U0_m_axi_gmem0_0_ARLEN,
        I_CH0_RVALID => gmem0_0_RVALID,
        I_CH0_RREADY => gemm_read_X_U0_m_axi_gmem0_0_RREADY,
        I_CH0_RDATA => gmem0_0_RDATA,
        I_CH0_RFIFONUM => gmem0_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem0_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem0_0_WREADY,
        I_CH0_WDATA => ap_const_lv512_lc_1,
        I_CH0_WSTRB => ap_const_lv64_0,
        I_CH0_BVALID => gmem0_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem1_m_axi_U : component gemm_stage_gmem1_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM1_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM1_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM1_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM1_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM1_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM1_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM1_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM1_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM1_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM1_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM1_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 512,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_gmem1_AWVALID,
        AWREADY => m_axi_gmem1_AWREADY,
        AWADDR => m_axi_gmem1_AWADDR,
        AWID => m_axi_gmem1_AWID,
        AWLEN => m_axi_gmem1_AWLEN,
        AWSIZE => m_axi_gmem1_AWSIZE,
        AWBURST => m_axi_gmem1_AWBURST,
        AWLOCK => m_axi_gmem1_AWLOCK,
        AWCACHE => m_axi_gmem1_AWCACHE,
        AWPROT => m_axi_gmem1_AWPROT,
        AWQOS => m_axi_gmem1_AWQOS,
        AWREGION => m_axi_gmem1_AWREGION,
        AWUSER => m_axi_gmem1_AWUSER,
        WVALID => m_axi_gmem1_WVALID,
        WREADY => m_axi_gmem1_WREADY,
        WDATA => m_axi_gmem1_WDATA,
        WSTRB => m_axi_gmem1_WSTRB,
        WLAST => m_axi_gmem1_WLAST,
        WID => m_axi_gmem1_WID,
        WUSER => m_axi_gmem1_WUSER,
        ARVALID => m_axi_gmem1_ARVALID,
        ARREADY => m_axi_gmem1_ARREADY,
        ARADDR => m_axi_gmem1_ARADDR,
        ARID => m_axi_gmem1_ARID,
        ARLEN => m_axi_gmem1_ARLEN,
        ARSIZE => m_axi_gmem1_ARSIZE,
        ARBURST => m_axi_gmem1_ARBURST,
        ARLOCK => m_axi_gmem1_ARLOCK,
        ARCACHE => m_axi_gmem1_ARCACHE,
        ARPROT => m_axi_gmem1_ARPROT,
        ARQOS => m_axi_gmem1_ARQOS,
        ARREGION => m_axi_gmem1_ARREGION,
        ARUSER => m_axi_gmem1_ARUSER,
        RVALID => m_axi_gmem1_RVALID,
        RREADY => m_axi_gmem1_RREADY,
        RDATA => m_axi_gmem1_RDATA,
        RLAST => m_axi_gmem1_RLAST,
        RID => m_axi_gmem1_RID,
        RUSER => m_axi_gmem1_RUSER,
        RRESP => m_axi_gmem1_RRESP,
        BVALID => m_axi_gmem1_BVALID,
        BREADY => m_axi_gmem1_BREADY,
        BRESP => m_axi_gmem1_BRESP,
        BID => m_axi_gmem1_BID,
        BUSER => m_axi_gmem1_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gemm_read_W_U0_m_axi_gmem1_0_ARVALID,
        I_CH0_ARREADY => gmem1_0_ARREADY,
        I_CH0_ARADDR => gemm_read_W_U0_m_axi_gmem1_0_ARADDR,
        I_CH0_ARLEN => gemm_read_W_U0_m_axi_gmem1_0_ARLEN,
        I_CH0_RVALID => gmem1_0_RVALID,
        I_CH0_RREADY => gemm_read_W_U0_m_axi_gmem1_0_RREADY,
        I_CH0_RDATA => gmem1_0_RDATA,
        I_CH0_RFIFONUM => gmem1_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => gmem1_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => gmem1_0_WREADY,
        I_CH0_WDATA => ap_const_lv512_lc_1,
        I_CH0_WSTRB => ap_const_lv64_0,
        I_CH0_BVALID => gmem1_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    gmem2_m_axi_U : component gemm_stage_gmem2_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM2_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM2_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM2_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM2_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM2_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM2_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM2_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM2_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM2_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM2_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM2_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 512,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem2_AWVALID,
        AWREADY => m_axi_gmem2_AWREADY,
        AWADDR => m_axi_gmem2_AWADDR,
        AWID => m_axi_gmem2_AWID,
        AWLEN => m_axi_gmem2_AWLEN,
        AWSIZE => m_axi_gmem2_AWSIZE,
        AWBURST => m_axi_gmem2_AWBURST,
        AWLOCK => m_axi_gmem2_AWLOCK,
        AWCACHE => m_axi_gmem2_AWCACHE,
        AWPROT => m_axi_gmem2_AWPROT,
        AWQOS => m_axi_gmem2_AWQOS,
        AWREGION => m_axi_gmem2_AWREGION,
        AWUSER => m_axi_gmem2_AWUSER,
        WVALID => m_axi_gmem2_WVALID,
        WREADY => m_axi_gmem2_WREADY,
        WDATA => m_axi_gmem2_WDATA,
        WSTRB => m_axi_gmem2_WSTRB,
        WLAST => m_axi_gmem2_WLAST,
        WID => m_axi_gmem2_WID,
        WUSER => m_axi_gmem2_WUSER,
        ARVALID => m_axi_gmem2_ARVALID,
        ARREADY => m_axi_gmem2_ARREADY,
        ARADDR => m_axi_gmem2_ARADDR,
        ARID => m_axi_gmem2_ARID,
        ARLEN => m_axi_gmem2_ARLEN,
        ARSIZE => m_axi_gmem2_ARSIZE,
        ARBURST => m_axi_gmem2_ARBURST,
        ARLOCK => m_axi_gmem2_ARLOCK,
        ARCACHE => m_axi_gmem2_ARCACHE,
        ARPROT => m_axi_gmem2_ARPROT,
        ARQOS => m_axi_gmem2_ARQOS,
        ARREGION => m_axi_gmem2_ARREGION,
        ARUSER => m_axi_gmem2_ARUSER,
        RVALID => m_axi_gmem2_RVALID,
        RREADY => m_axi_gmem2_RREADY,
        RDATA => m_axi_gmem2_RDATA,
        RLAST => m_axi_gmem2_RLAST,
        RID => m_axi_gmem2_RID,
        RUSER => m_axi_gmem2_RUSER,
        RRESP => m_axi_gmem2_RRESP,
        BVALID => m_axi_gmem2_BVALID,
        BREADY => m_axi_gmem2_BREADY,
        BRESP => m_axi_gmem2_BRESP,
        BID => m_axi_gmem2_BID,
        BUSER => m_axi_gmem2_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => gmem2_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => gmem2_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => gmem2_0_RDATA,
        I_CH0_RFIFONUM => gmem2_0_RFIFONUM,
        I_CH0_AWVALID => gemm_write_U0_m_axi_gmem2_0_AWVALID,
        I_CH0_AWREADY => gmem2_0_AWREADY,
        I_CH0_AWADDR => gemm_write_U0_m_axi_gmem2_0_AWADDR,
        I_CH0_AWLEN => gemm_write_U0_m_axi_gmem2_0_AWLEN,
        I_CH0_WVALID => gemm_write_U0_m_axi_gmem2_0_WVALID,
        I_CH0_WREADY => gmem2_0_WREADY,
        I_CH0_WDATA => gemm_write_U0_m_axi_gmem2_0_WDATA,
        I_CH0_WSTRB => gemm_write_U0_m_axi_gmem2_0_WSTRB,
        I_CH0_BVALID => gmem2_0_BVALID,
        I_CH0_BREADY => gemm_write_U0_m_axi_gmem2_0_BREADY);

    entry_proc_U0 : component gemm_stage_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_gemm_write_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        H_temp => H_temp,
        H_temp_c_din => entry_proc_U0_H_temp_c_din,
        H_temp_c_full_n => H_temp_c_full_n,
        H_temp_c_write => entry_proc_U0_H_temp_c_write,
        H_temp_c_num_data_valid => H_temp_c_num_data_valid,
        H_temp_c_fifo_cap => H_temp_c_fifo_cap);

    gemm_read_X_U0 : component gemm_stage_gemm_read_X
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => gemm_read_X_U0_ap_start,
        start_full_n => start_for_gemm_compute_U0_full_n,
        ap_done => gemm_read_X_U0_ap_done,
        ap_continue => gemm_read_X_U0_ap_continue,
        ap_idle => gemm_read_X_U0_ap_idle,
        ap_ready => gemm_read_X_U0_ap_ready,
        m_axi_gmem0_0_AWVALID => gemm_read_X_U0_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_0_AWADDR => gemm_read_X_U0_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => gemm_read_X_U0_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => gemm_read_X_U0_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => gemm_read_X_U0_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => gemm_read_X_U0_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => gemm_read_X_U0_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => gemm_read_X_U0_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => gemm_read_X_U0_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => gemm_read_X_U0_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => gemm_read_X_U0_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => gemm_read_X_U0_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => gemm_read_X_U0_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => ap_const_logic_0,
        m_axi_gmem0_0_WDATA => gemm_read_X_U0_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => gemm_read_X_U0_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => gemm_read_X_U0_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => gemm_read_X_U0_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => gemm_read_X_U0_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => gemm_read_X_U0_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR => gemm_read_X_U0_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => gemm_read_X_U0_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => gemm_read_X_U0_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => gemm_read_X_U0_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => gemm_read_X_U0_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => gemm_read_X_U0_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => gemm_read_X_U0_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => gemm_read_X_U0_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => gemm_read_X_U0_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => gemm_read_X_U0_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => gemm_read_X_U0_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY => gemm_read_X_U0_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST => gmem0_0_RLAST,
        m_axi_gmem0_0_RID => gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM => gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER => gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP => gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID => ap_const_logic_0,
        m_axi_gmem0_0_BREADY => gemm_read_X_U0_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BID => ap_const_lv1_0,
        m_axi_gmem0_0_BUSER => ap_const_lv1_0,
        X_stream_din => gemm_read_X_U0_X_stream_din,
        X_stream_full_n => X_stream_full_n,
        X_stream_write => gemm_read_X_U0_X_stream_write,
        X_stream_num_data_valid => X_stream_num_data_valid,
        X_stream_fifo_cap => X_stream_fifo_cap,
        start_out => gemm_read_X_U0_start_out,
        start_write => gemm_read_X_U0_start_write,
        X => X);

    gemm_read_W_U0 : component gemm_stage_gemm_read_W
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => gemm_read_W_U0_ap_start,
        ap_done => gemm_read_W_U0_ap_done,
        ap_continue => gemm_read_W_U0_ap_continue,
        ap_idle => gemm_read_W_U0_ap_idle,
        ap_ready => gemm_read_W_U0_ap_ready,
        m_axi_gmem1_0_AWVALID => gemm_read_W_U0_m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY => ap_const_logic_0,
        m_axi_gmem1_0_AWADDR => gemm_read_W_U0_m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID => gemm_read_W_U0_m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN => gemm_read_W_U0_m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE => gemm_read_W_U0_m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST => gemm_read_W_U0_m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK => gemm_read_W_U0_m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE => gemm_read_W_U0_m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT => gemm_read_W_U0_m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS => gemm_read_W_U0_m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION => gemm_read_W_U0_m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER => gemm_read_W_U0_m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID => gemm_read_W_U0_m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY => ap_const_logic_0,
        m_axi_gmem1_0_WDATA => gemm_read_W_U0_m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB => gemm_read_W_U0_m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST => gemm_read_W_U0_m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID => gemm_read_W_U0_m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER => gemm_read_W_U0_m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID => gemm_read_W_U0_m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY => gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR => gemm_read_W_U0_m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID => gemm_read_W_U0_m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN => gemm_read_W_U0_m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE => gemm_read_W_U0_m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST => gemm_read_W_U0_m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK => gemm_read_W_U0_m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE => gemm_read_W_U0_m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT => gemm_read_W_U0_m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS => gemm_read_W_U0_m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION => gemm_read_W_U0_m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER => gemm_read_W_U0_m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID => gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY => gemm_read_W_U0_m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA => gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST => gmem1_0_RLAST,
        m_axi_gmem1_0_RID => gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM => gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER => gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP => gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID => ap_const_logic_0,
        m_axi_gmem1_0_BREADY => gemm_read_W_U0_m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP => ap_const_lv2_0,
        m_axi_gmem1_0_BID => ap_const_lv1_0,
        m_axi_gmem1_0_BUSER => ap_const_lv1_0,
        W_stream_din => gemm_read_W_U0_W_stream_din,
        W_stream_full_n => W_stream_full_n,
        W_stream_write => gemm_read_W_U0_W_stream_write,
        W_stream_num_data_valid => W_stream_num_data_valid,
        W_stream_fifo_cap => W_stream_fifo_cap,
        W => W);

    gemm_compute_U0 : component gemm_stage_gemm_compute
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => gemm_compute_U0_ap_start,
        ap_done => gemm_compute_U0_ap_done,
        ap_continue => gemm_compute_U0_ap_continue,
        ap_idle => gemm_compute_U0_ap_idle,
        ap_ready => gemm_compute_U0_ap_ready,
        X_stream_dout => X_stream_dout,
        X_stream_empty_n => X_stream_empty_n,
        X_stream_read => gemm_compute_U0_X_stream_read,
        X_stream_num_data_valid => X_stream_num_data_valid,
        X_stream_fifo_cap => X_stream_fifo_cap,
        W_stream_dout => W_stream_dout,
        W_stream_empty_n => W_stream_empty_n,
        W_stream_read => gemm_compute_U0_W_stream_read,
        W_stream_num_data_valid => W_stream_num_data_valid,
        W_stream_fifo_cap => W_stream_fifo_cap,
        XW_stream_din => gemm_compute_U0_XW_stream_din,
        XW_stream_full_n => XW_stream_full_n,
        XW_stream_write => gemm_compute_U0_XW_stream_write,
        XW_stream_num_data_valid => gemm_compute_U0_XW_stream_num_data_valid,
        XW_stream_fifo_cap => gemm_compute_U0_XW_stream_fifo_cap);

    gemm_write_U0 : component gemm_stage_gemm_write
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => gemm_write_U0_ap_start,
        ap_done => gemm_write_U0_ap_done,
        ap_continue => gemm_write_U0_ap_continue,
        ap_idle => gemm_write_U0_ap_idle,
        ap_ready => gemm_write_U0_ap_ready,
        H_temp_dout => H_temp_c_dout,
        H_temp_empty_n => H_temp_c_empty_n,
        H_temp_read => gemm_write_U0_H_temp_read,
        H_temp_num_data_valid => H_temp_c_num_data_valid,
        H_temp_fifo_cap => H_temp_c_fifo_cap,
        m_axi_gmem2_0_AWVALID => gemm_write_U0_m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY => gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR => gemm_write_U0_m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID => gemm_write_U0_m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN => gemm_write_U0_m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE => gemm_write_U0_m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST => gemm_write_U0_m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK => gemm_write_U0_m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE => gemm_write_U0_m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT => gemm_write_U0_m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS => gemm_write_U0_m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION => gemm_write_U0_m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER => gemm_write_U0_m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID => gemm_write_U0_m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY => gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA => gemm_write_U0_m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB => gemm_write_U0_m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST => gemm_write_U0_m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID => gemm_write_U0_m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER => gemm_write_U0_m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID => gemm_write_U0_m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY => ap_const_logic_0,
        m_axi_gmem2_0_ARADDR => gemm_write_U0_m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID => gemm_write_U0_m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN => gemm_write_U0_m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE => gemm_write_U0_m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST => gemm_write_U0_m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK => gemm_write_U0_m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE => gemm_write_U0_m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT => gemm_write_U0_m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS => gemm_write_U0_m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION => gemm_write_U0_m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER => gemm_write_U0_m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID => ap_const_logic_0,
        m_axi_gmem2_0_RREADY => gemm_write_U0_m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA => ap_const_lv512_lc_1,
        m_axi_gmem2_0_RLAST => ap_const_logic_0,
        m_axi_gmem2_0_RID => ap_const_lv1_0,
        m_axi_gmem2_0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem2_0_RUSER => ap_const_lv1_0,
        m_axi_gmem2_0_RRESP => ap_const_lv2_0,
        m_axi_gmem2_0_BVALID => gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY => gemm_write_U0_m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP => gmem2_0_BRESP,
        m_axi_gmem2_0_BID => gmem2_0_BID,
        m_axi_gmem2_0_BUSER => gmem2_0_BUSER,
        XW_stream_dout => XW_stream_dout,
        XW_stream_empty_n => XW_stream_empty_n,
        XW_stream_read => gemm_write_U0_XW_stream_read,
        XW_stream_num_data_valid => XW_stream_num_data_valid,
        XW_stream_fifo_cap => XW_stream_fifo_cap);

    H_temp_c_U : component gemm_stage_fifo_w64_d4_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_H_temp_c_din,
        if_full_n => H_temp_c_full_n,
        if_write => entry_proc_U0_H_temp_c_write,
        if_dout => H_temp_c_dout,
        if_empty_n => H_temp_c_empty_n,
        if_read => gemm_write_U0_H_temp_read,
        if_num_data_valid => H_temp_c_num_data_valid,
        if_fifo_cap => H_temp_c_fifo_cap);

    X_stream_U : component gemm_stage_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_read_X_U0_X_stream_din,
        if_full_n => X_stream_full_n,
        if_write => gemm_read_X_U0_X_stream_write,
        if_dout => X_stream_dout,
        if_empty_n => X_stream_empty_n,
        if_read => gemm_compute_U0_X_stream_read,
        if_num_data_valid => X_stream_num_data_valid,
        if_fifo_cap => X_stream_fifo_cap);

    W_stream_U : component gemm_stage_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_read_W_U0_W_stream_din,
        if_full_n => W_stream_full_n,
        if_write => gemm_read_W_U0_W_stream_write,
        if_dout => W_stream_dout,
        if_empty_n => W_stream_empty_n,
        if_read => gemm_compute_U0_W_stream_read,
        if_num_data_valid => W_stream_num_data_valid,
        if_fifo_cap => W_stream_fifo_cap);

    XW_stream_U : component gemm_stage_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_compute_U0_XW_stream_din,
        if_full_n => XW_stream_full_n,
        if_write => gemm_compute_U0_XW_stream_write,
        if_dout => XW_stream_dout,
        if_empty_n => XW_stream_empty_n,
        if_read => gemm_write_U0_XW_stream_read,
        if_num_data_valid => XW_stream_num_data_valid,
        if_fifo_cap => XW_stream_fifo_cap);

    start_for_gemm_write_U0_U : component gemm_stage_start_for_gemm_write_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_gemm_write_U0_din,
        if_full_n => start_for_gemm_write_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_gemm_write_U0_dout,
        if_empty_n => start_for_gemm_write_U0_empty_n,
        if_read => gemm_write_U0_ap_ready);

    start_for_gemm_compute_U0_U : component gemm_stage_start_for_gemm_compute_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_gemm_compute_U0_din,
        if_full_n => start_for_gemm_compute_U0_full_n,
        if_write => gemm_read_X_U0_start_write,
        if_dout => start_for_gemm_compute_U0_dout,
        if_empty_n => start_for_gemm_compute_U0_empty_n,
        if_read => gemm_compute_U0_ap_ready);





    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_gemm_read_W_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_sync_gemm_read_W_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_gemm_read_X_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_sync_gemm_read_X_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    ap_done <= gemm_write_U0_ap_done;
    ap_idle <= (gemm_write_U0_ap_idle and gemm_read_X_U0_ap_idle and gemm_read_W_U0_ap_idle and gemm_compute_U0_ap_idle and entry_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_gemm_read_W_U0_ap_ready <= (gemm_read_W_U0_ap_ready or ap_sync_reg_gemm_read_W_U0_ap_ready);
    ap_sync_gemm_read_X_U0_ap_ready <= (gemm_read_X_U0_ap_ready or ap_sync_reg_gemm_read_X_U0_ap_ready);
    ap_sync_ready <= (ap_sync_gemm_read_X_U0_ap_ready and ap_sync_gemm_read_W_U0_ap_ready and ap_sync_entry_proc_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    gemm_compute_U0_XW_stream_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(XW_stream_fifo_cap),5))),32));
    gemm_compute_U0_XW_stream_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(XW_stream_num_data_valid),5))),32));
    gemm_compute_U0_ap_continue <= ap_const_logic_1;
    gemm_compute_U0_ap_start <= start_for_gemm_compute_U0_empty_n;
    gemm_read_W_U0_ap_continue <= ap_const_logic_1;
    gemm_read_W_U0_ap_start <= ((ap_sync_reg_gemm_read_W_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    gemm_read_X_U0_ap_continue <= ap_const_logic_1;
    gemm_read_X_U0_ap_start <= ((ap_sync_reg_gemm_read_X_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    gemm_write_U0_ap_continue <= ap_const_logic_1;
    gemm_write_U0_ap_start <= start_for_gemm_write_U0_empty_n;
    gmem0_0_RID <= ap_const_lv1_0;
    gmem0_0_RLAST <= ap_const_logic_0;
    gmem0_0_RRESP <= ap_const_lv2_0;
    gmem0_0_RUSER <= ap_const_lv1_0;
    gmem1_0_RID <= ap_const_lv1_0;
    gmem1_0_RLAST <= ap_const_logic_0;
    gmem1_0_RRESP <= ap_const_lv2_0;
    gmem1_0_RUSER <= ap_const_lv1_0;
    gmem2_0_BID <= ap_const_lv1_0;
    gmem2_0_BRESP <= ap_const_lv2_0;
    gmem2_0_BUSER <= ap_const_lv1_0;
    start_for_gemm_compute_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_gemm_write_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
