// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module integrated_gcn_spmm_compute_Pipeline_SPMM_LOAD_H (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY,
        m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID,
        m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA,
        m_axi_gmem2_0_RLAST,
        m_axi_gmem2_0_RID,
        m_axi_gmem2_0_RFIFONUM,
        m_axi_gmem2_0_RUSER,
        m_axi_gmem2_0_RRESP,
        m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER,
        sext_ln255_1,
        h_buf_31_address0,
        h_buf_31_ce0,
        h_buf_31_we0,
        h_buf_31_d0,
        h_buf_30_address0,
        h_buf_30_ce0,
        h_buf_30_we0,
        h_buf_30_d0,
        h_buf_29_address0,
        h_buf_29_ce0,
        h_buf_29_we0,
        h_buf_29_d0,
        h_buf_28_address0,
        h_buf_28_ce0,
        h_buf_28_we0,
        h_buf_28_d0,
        h_buf_27_address0,
        h_buf_27_ce0,
        h_buf_27_we0,
        h_buf_27_d0,
        h_buf_26_address0,
        h_buf_26_ce0,
        h_buf_26_we0,
        h_buf_26_d0,
        h_buf_25_address0,
        h_buf_25_ce0,
        h_buf_25_we0,
        h_buf_25_d0,
        h_buf_24_address0,
        h_buf_24_ce0,
        h_buf_24_we0,
        h_buf_24_d0,
        h_buf_23_address0,
        h_buf_23_ce0,
        h_buf_23_we0,
        h_buf_23_d0,
        h_buf_22_address0,
        h_buf_22_ce0,
        h_buf_22_we0,
        h_buf_22_d0,
        h_buf_21_address0,
        h_buf_21_ce0,
        h_buf_21_we0,
        h_buf_21_d0,
        h_buf_20_address0,
        h_buf_20_ce0,
        h_buf_20_we0,
        h_buf_20_d0,
        h_buf_19_address0,
        h_buf_19_ce0,
        h_buf_19_we0,
        h_buf_19_d0,
        h_buf_18_address0,
        h_buf_18_ce0,
        h_buf_18_we0,
        h_buf_18_d0,
        h_buf_17_address0,
        h_buf_17_ce0,
        h_buf_17_we0,
        h_buf_17_d0,
        h_buf_16_address0,
        h_buf_16_ce0,
        h_buf_16_we0,
        h_buf_16_d0,
        h_buf_15_address0,
        h_buf_15_ce0,
        h_buf_15_we0,
        h_buf_15_d0,
        h_buf_14_address0,
        h_buf_14_ce0,
        h_buf_14_we0,
        h_buf_14_d0,
        h_buf_13_address0,
        h_buf_13_ce0,
        h_buf_13_we0,
        h_buf_13_d0,
        h_buf_12_address0,
        h_buf_12_ce0,
        h_buf_12_we0,
        h_buf_12_d0,
        h_buf_11_address0,
        h_buf_11_ce0,
        h_buf_11_we0,
        h_buf_11_d0,
        h_buf_10_address0,
        h_buf_10_ce0,
        h_buf_10_we0,
        h_buf_10_d0,
        h_buf_9_address0,
        h_buf_9_ce0,
        h_buf_9_we0,
        h_buf_9_d0,
        h_buf_8_address0,
        h_buf_8_ce0,
        h_buf_8_we0,
        h_buf_8_d0,
        h_buf_7_address0,
        h_buf_7_ce0,
        h_buf_7_we0,
        h_buf_7_d0,
        h_buf_6_address0,
        h_buf_6_ce0,
        h_buf_6_we0,
        h_buf_6_d0,
        h_buf_5_address0,
        h_buf_5_ce0,
        h_buf_5_we0,
        h_buf_5_d0,
        h_buf_4_address0,
        h_buf_4_ce0,
        h_buf_4_we0,
        h_buf_4_d0,
        h_buf_3_address0,
        h_buf_3_ce0,
        h_buf_3_we0,
        h_buf_3_d0,
        h_buf_2_address0,
        h_buf_2_ce0,
        h_buf_2_we0,
        h_buf_2_d0,
        h_buf_1_address0,
        h_buf_1_ce0,
        h_buf_1_we0,
        h_buf_1_d0,
        h_buf_address0,
        h_buf_ce0,
        h_buf_we0,
        h_buf_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem2_0_AWVALID;
input   m_axi_gmem2_0_AWREADY;
output  [63:0] m_axi_gmem2_0_AWADDR;
output  [0:0] m_axi_gmem2_0_AWID;
output  [31:0] m_axi_gmem2_0_AWLEN;
output  [2:0] m_axi_gmem2_0_AWSIZE;
output  [1:0] m_axi_gmem2_0_AWBURST;
output  [1:0] m_axi_gmem2_0_AWLOCK;
output  [3:0] m_axi_gmem2_0_AWCACHE;
output  [2:0] m_axi_gmem2_0_AWPROT;
output  [3:0] m_axi_gmem2_0_AWQOS;
output  [3:0] m_axi_gmem2_0_AWREGION;
output  [0:0] m_axi_gmem2_0_AWUSER;
output   m_axi_gmem2_0_WVALID;
input   m_axi_gmem2_0_WREADY;
output  [511:0] m_axi_gmem2_0_WDATA;
output  [63:0] m_axi_gmem2_0_WSTRB;
output   m_axi_gmem2_0_WLAST;
output  [0:0] m_axi_gmem2_0_WID;
output  [0:0] m_axi_gmem2_0_WUSER;
output   m_axi_gmem2_0_ARVALID;
input   m_axi_gmem2_0_ARREADY;
output  [63:0] m_axi_gmem2_0_ARADDR;
output  [0:0] m_axi_gmem2_0_ARID;
output  [31:0] m_axi_gmem2_0_ARLEN;
output  [2:0] m_axi_gmem2_0_ARSIZE;
output  [1:0] m_axi_gmem2_0_ARBURST;
output  [1:0] m_axi_gmem2_0_ARLOCK;
output  [3:0] m_axi_gmem2_0_ARCACHE;
output  [2:0] m_axi_gmem2_0_ARPROT;
output  [3:0] m_axi_gmem2_0_ARQOS;
output  [3:0] m_axi_gmem2_0_ARREGION;
output  [0:0] m_axi_gmem2_0_ARUSER;
input   m_axi_gmem2_0_RVALID;
output   m_axi_gmem2_0_RREADY;
input  [511:0] m_axi_gmem2_0_RDATA;
input   m_axi_gmem2_0_RLAST;
input  [0:0] m_axi_gmem2_0_RID;
input  [8:0] m_axi_gmem2_0_RFIFONUM;
input  [0:0] m_axi_gmem2_0_RUSER;
input  [1:0] m_axi_gmem2_0_RRESP;
input   m_axi_gmem2_0_BVALID;
output   m_axi_gmem2_0_BREADY;
input  [1:0] m_axi_gmem2_0_BRESP;
input  [0:0] m_axi_gmem2_0_BID;
input  [0:0] m_axi_gmem2_0_BUSER;
input  [57:0] sext_ln255_1;
output  [0:0] h_buf_31_address0;
output   h_buf_31_ce0;
output   h_buf_31_we0;
output  [15:0] h_buf_31_d0;
output  [0:0] h_buf_30_address0;
output   h_buf_30_ce0;
output   h_buf_30_we0;
output  [15:0] h_buf_30_d0;
output  [0:0] h_buf_29_address0;
output   h_buf_29_ce0;
output   h_buf_29_we0;
output  [15:0] h_buf_29_d0;
output  [0:0] h_buf_28_address0;
output   h_buf_28_ce0;
output   h_buf_28_we0;
output  [15:0] h_buf_28_d0;
output  [0:0] h_buf_27_address0;
output   h_buf_27_ce0;
output   h_buf_27_we0;
output  [15:0] h_buf_27_d0;
output  [0:0] h_buf_26_address0;
output   h_buf_26_ce0;
output   h_buf_26_we0;
output  [15:0] h_buf_26_d0;
output  [0:0] h_buf_25_address0;
output   h_buf_25_ce0;
output   h_buf_25_we0;
output  [15:0] h_buf_25_d0;
output  [0:0] h_buf_24_address0;
output   h_buf_24_ce0;
output   h_buf_24_we0;
output  [15:0] h_buf_24_d0;
output  [0:0] h_buf_23_address0;
output   h_buf_23_ce0;
output   h_buf_23_we0;
output  [15:0] h_buf_23_d0;
output  [0:0] h_buf_22_address0;
output   h_buf_22_ce0;
output   h_buf_22_we0;
output  [15:0] h_buf_22_d0;
output  [0:0] h_buf_21_address0;
output   h_buf_21_ce0;
output   h_buf_21_we0;
output  [15:0] h_buf_21_d0;
output  [0:0] h_buf_20_address0;
output   h_buf_20_ce0;
output   h_buf_20_we0;
output  [15:0] h_buf_20_d0;
output  [0:0] h_buf_19_address0;
output   h_buf_19_ce0;
output   h_buf_19_we0;
output  [15:0] h_buf_19_d0;
output  [0:0] h_buf_18_address0;
output   h_buf_18_ce0;
output   h_buf_18_we0;
output  [15:0] h_buf_18_d0;
output  [0:0] h_buf_17_address0;
output   h_buf_17_ce0;
output   h_buf_17_we0;
output  [15:0] h_buf_17_d0;
output  [0:0] h_buf_16_address0;
output   h_buf_16_ce0;
output   h_buf_16_we0;
output  [15:0] h_buf_16_d0;
output  [0:0] h_buf_15_address0;
output   h_buf_15_ce0;
output   h_buf_15_we0;
output  [15:0] h_buf_15_d0;
output  [0:0] h_buf_14_address0;
output   h_buf_14_ce0;
output   h_buf_14_we0;
output  [15:0] h_buf_14_d0;
output  [0:0] h_buf_13_address0;
output   h_buf_13_ce0;
output   h_buf_13_we0;
output  [15:0] h_buf_13_d0;
output  [0:0] h_buf_12_address0;
output   h_buf_12_ce0;
output   h_buf_12_we0;
output  [15:0] h_buf_12_d0;
output  [0:0] h_buf_11_address0;
output   h_buf_11_ce0;
output   h_buf_11_we0;
output  [15:0] h_buf_11_d0;
output  [0:0] h_buf_10_address0;
output   h_buf_10_ce0;
output   h_buf_10_we0;
output  [15:0] h_buf_10_d0;
output  [0:0] h_buf_9_address0;
output   h_buf_9_ce0;
output   h_buf_9_we0;
output  [15:0] h_buf_9_d0;
output  [0:0] h_buf_8_address0;
output   h_buf_8_ce0;
output   h_buf_8_we0;
output  [15:0] h_buf_8_d0;
output  [0:0] h_buf_7_address0;
output   h_buf_7_ce0;
output   h_buf_7_we0;
output  [15:0] h_buf_7_d0;
output  [0:0] h_buf_6_address0;
output   h_buf_6_ce0;
output   h_buf_6_we0;
output  [15:0] h_buf_6_d0;
output  [0:0] h_buf_5_address0;
output   h_buf_5_ce0;
output   h_buf_5_we0;
output  [15:0] h_buf_5_d0;
output  [0:0] h_buf_4_address0;
output   h_buf_4_ce0;
output   h_buf_4_we0;
output  [15:0] h_buf_4_d0;
output  [0:0] h_buf_3_address0;
output   h_buf_3_ce0;
output   h_buf_3_we0;
output  [15:0] h_buf_3_d0;
output  [0:0] h_buf_2_address0;
output   h_buf_2_ce0;
output   h_buf_2_we0;
output  [15:0] h_buf_2_d0;
output  [0:0] h_buf_1_address0;
output   h_buf_1_ce0;
output   h_buf_1_we0;
output  [15:0] h_buf_1_d0;
output  [0:0] h_buf_address0;
output   h_buf_ce0;
output   h_buf_we0;
output  [15:0] h_buf_d0;

reg ap_idle;
reg m_axi_gmem2_0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln255_fu_681_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem2_blk_n_R;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [1:0] v_1_reg_1065;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] v_1_reg_1065_pp0_iter1_reg;
wire   [15:0] trunc_ln257_fu_704_p1;
reg   [15:0] trunc_ln257_reg_1074;
reg   [15:0] trunc_ln257_1_reg_1079;
reg   [15:0] trunc_ln257_2_reg_1084;
reg   [15:0] trunc_ln257_3_reg_1089;
reg   [15:0] trunc_ln257_4_reg_1094;
reg   [15:0] trunc_ln257_5_reg_1099;
reg   [15:0] trunc_ln257_6_reg_1104;
reg   [15:0] trunc_ln257_7_reg_1109;
reg   [15:0] trunc_ln257_8_reg_1114;
reg   [15:0] trunc_ln257_9_reg_1119;
reg   [15:0] trunc_ln257_s_reg_1124;
reg   [15:0] trunc_ln257_10_reg_1129;
reg   [15:0] trunc_ln257_11_reg_1134;
reg   [15:0] trunc_ln257_12_reg_1139;
reg   [15:0] trunc_ln257_13_reg_1144;
reg   [15:0] trunc_ln257_14_reg_1149;
reg   [15:0] trunc_ln257_15_reg_1154;
reg   [15:0] trunc_ln257_16_reg_1159;
reg   [15:0] trunc_ln257_17_reg_1164;
reg   [15:0] trunc_ln257_18_reg_1169;
reg   [15:0] trunc_ln257_19_reg_1174;
reg   [15:0] trunc_ln257_20_reg_1179;
reg   [15:0] trunc_ln257_21_reg_1184;
reg   [15:0] trunc_ln257_22_reg_1189;
reg   [15:0] trunc_ln257_23_reg_1194;
reg   [15:0] trunc_ln257_24_reg_1199;
reg   [15:0] trunc_ln257_25_reg_1204;
reg   [15:0] trunc_ln257_26_reg_1209;
reg   [15:0] trunc_ln257_27_reg_1214;
reg   [15:0] trunc_ln257_28_reg_1219;
reg   [15:0] trunc_ln257_29_reg_1224;
reg   [15:0] trunc_ln257_30_reg_1229;
wire   [63:0] zext_ln255_fu_1018_p1;
wire    ap_block_pp0_stage0_grp0;
reg   [1:0] v_fu_238;
wire   [1:0] add_ln255_fu_687_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_v_1;
wire    ap_block_pp0_stage0;
reg    h_buf_we0_local;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    h_buf_ce0_local;
reg    h_buf_1_we0_local;
reg    h_buf_1_ce0_local;
reg    h_buf_2_we0_local;
reg    h_buf_2_ce0_local;
reg    h_buf_3_we0_local;
reg    h_buf_3_ce0_local;
reg    h_buf_4_we0_local;
reg    h_buf_4_ce0_local;
reg    h_buf_5_we0_local;
reg    h_buf_5_ce0_local;
reg    h_buf_6_we0_local;
reg    h_buf_6_ce0_local;
reg    h_buf_7_we0_local;
reg    h_buf_7_ce0_local;
reg    h_buf_8_we0_local;
reg    h_buf_8_ce0_local;
reg    h_buf_9_we0_local;
reg    h_buf_9_ce0_local;
reg    h_buf_10_we0_local;
reg    h_buf_10_ce0_local;
reg    h_buf_11_we0_local;
reg    h_buf_11_ce0_local;
reg    h_buf_12_we0_local;
reg    h_buf_12_ce0_local;
reg    h_buf_13_we0_local;
reg    h_buf_13_ce0_local;
reg    h_buf_14_we0_local;
reg    h_buf_14_ce0_local;
reg    h_buf_15_we0_local;
reg    h_buf_15_ce0_local;
reg    h_buf_16_we0_local;
reg    h_buf_16_ce0_local;
reg    h_buf_17_we0_local;
reg    h_buf_17_ce0_local;
reg    h_buf_18_we0_local;
reg    h_buf_18_ce0_local;
reg    h_buf_19_we0_local;
reg    h_buf_19_ce0_local;
reg    h_buf_20_we0_local;
reg    h_buf_20_ce0_local;
reg    h_buf_21_we0_local;
reg    h_buf_21_ce0_local;
reg    h_buf_22_we0_local;
reg    h_buf_22_ce0_local;
reg    h_buf_23_we0_local;
reg    h_buf_23_ce0_local;
reg    h_buf_24_we0_local;
reg    h_buf_24_ce0_local;
reg    h_buf_25_we0_local;
reg    h_buf_25_ce0_local;
reg    h_buf_26_we0_local;
reg    h_buf_26_ce0_local;
reg    h_buf_27_we0_local;
reg    h_buf_27_ce0_local;
reg    h_buf_28_we0_local;
reg    h_buf_28_ce0_local;
reg    h_buf_29_we0_local;
reg    h_buf_29_ce0_local;
reg    h_buf_30_we0_local;
reg    h_buf_30_ce0_local;
reg    h_buf_31_we0_local;
reg    h_buf_31_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 v_fu_238 = 2'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

integrated_gcn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln255_fu_681_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            v_fu_238 <= add_ln255_fu_687_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            v_fu_238 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        v_1_reg_1065 <= ap_sig_allocacmp_v_1;
        v_1_reg_1065_pp0_iter1_reg <= v_1_reg_1065;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln257_10_reg_1129 <= {{m_axi_gmem2_0_RDATA[191:176]}};
        trunc_ln257_11_reg_1134 <= {{m_axi_gmem2_0_RDATA[207:192]}};
        trunc_ln257_12_reg_1139 <= {{m_axi_gmem2_0_RDATA[223:208]}};
        trunc_ln257_13_reg_1144 <= {{m_axi_gmem2_0_RDATA[239:224]}};
        trunc_ln257_14_reg_1149 <= {{m_axi_gmem2_0_RDATA[255:240]}};
        trunc_ln257_15_reg_1154 <= {{m_axi_gmem2_0_RDATA[271:256]}};
        trunc_ln257_16_reg_1159 <= {{m_axi_gmem2_0_RDATA[287:272]}};
        trunc_ln257_17_reg_1164 <= {{m_axi_gmem2_0_RDATA[303:288]}};
        trunc_ln257_18_reg_1169 <= {{m_axi_gmem2_0_RDATA[319:304]}};
        trunc_ln257_19_reg_1174 <= {{m_axi_gmem2_0_RDATA[335:320]}};
        trunc_ln257_1_reg_1079 <= {{m_axi_gmem2_0_RDATA[31:16]}};
        trunc_ln257_20_reg_1179 <= {{m_axi_gmem2_0_RDATA[351:336]}};
        trunc_ln257_21_reg_1184 <= {{m_axi_gmem2_0_RDATA[367:352]}};
        trunc_ln257_22_reg_1189 <= {{m_axi_gmem2_0_RDATA[383:368]}};
        trunc_ln257_23_reg_1194 <= {{m_axi_gmem2_0_RDATA[399:384]}};
        trunc_ln257_24_reg_1199 <= {{m_axi_gmem2_0_RDATA[415:400]}};
        trunc_ln257_25_reg_1204 <= {{m_axi_gmem2_0_RDATA[431:416]}};
        trunc_ln257_26_reg_1209 <= {{m_axi_gmem2_0_RDATA[447:432]}};
        trunc_ln257_27_reg_1214 <= {{m_axi_gmem2_0_RDATA[463:448]}};
        trunc_ln257_28_reg_1219 <= {{m_axi_gmem2_0_RDATA[479:464]}};
        trunc_ln257_29_reg_1224 <= {{m_axi_gmem2_0_RDATA[495:480]}};
        trunc_ln257_2_reg_1084 <= {{m_axi_gmem2_0_RDATA[47:32]}};
        trunc_ln257_30_reg_1229 <= {{m_axi_gmem2_0_RDATA[511:496]}};
        trunc_ln257_3_reg_1089 <= {{m_axi_gmem2_0_RDATA[63:48]}};
        trunc_ln257_4_reg_1094 <= {{m_axi_gmem2_0_RDATA[79:64]}};
        trunc_ln257_5_reg_1099 <= {{m_axi_gmem2_0_RDATA[95:80]}};
        trunc_ln257_6_reg_1104 <= {{m_axi_gmem2_0_RDATA[111:96]}};
        trunc_ln257_7_reg_1109 <= {{m_axi_gmem2_0_RDATA[127:112]}};
        trunc_ln257_8_reg_1114 <= {{m_axi_gmem2_0_RDATA[143:128]}};
        trunc_ln257_9_reg_1119 <= {{m_axi_gmem2_0_RDATA[159:144]}};
        trunc_ln257_reg_1074 <= trunc_ln257_fu_704_p1;
        trunc_ln257_s_reg_1124 <= {{m_axi_gmem2_0_RDATA[175:160]}};
    end
end

always @ (*) begin
    if (((icmp_ln255_fu_681_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_v_1 = 2'd0;
    end else begin
        ap_sig_allocacmp_v_1 = v_fu_238;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        gmem2_blk_n_R = m_axi_gmem2_0_RVALID;
    end else begin
        gmem2_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_10_ce0_local = 1'b1;
    end else begin
        h_buf_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_10_we0_local = 1'b1;
    end else begin
        h_buf_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_11_ce0_local = 1'b1;
    end else begin
        h_buf_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_11_we0_local = 1'b1;
    end else begin
        h_buf_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_12_ce0_local = 1'b1;
    end else begin
        h_buf_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_12_we0_local = 1'b1;
    end else begin
        h_buf_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_13_ce0_local = 1'b1;
    end else begin
        h_buf_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_13_we0_local = 1'b1;
    end else begin
        h_buf_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_14_ce0_local = 1'b1;
    end else begin
        h_buf_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_14_we0_local = 1'b1;
    end else begin
        h_buf_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_15_ce0_local = 1'b1;
    end else begin
        h_buf_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_15_we0_local = 1'b1;
    end else begin
        h_buf_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_16_ce0_local = 1'b1;
    end else begin
        h_buf_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_16_we0_local = 1'b1;
    end else begin
        h_buf_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_17_ce0_local = 1'b1;
    end else begin
        h_buf_17_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_17_we0_local = 1'b1;
    end else begin
        h_buf_17_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_18_ce0_local = 1'b1;
    end else begin
        h_buf_18_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_18_we0_local = 1'b1;
    end else begin
        h_buf_18_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_19_ce0_local = 1'b1;
    end else begin
        h_buf_19_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_19_we0_local = 1'b1;
    end else begin
        h_buf_19_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_1_ce0_local = 1'b1;
    end else begin
        h_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_1_we0_local = 1'b1;
    end else begin
        h_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_20_ce0_local = 1'b1;
    end else begin
        h_buf_20_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_20_we0_local = 1'b1;
    end else begin
        h_buf_20_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_21_ce0_local = 1'b1;
    end else begin
        h_buf_21_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_21_we0_local = 1'b1;
    end else begin
        h_buf_21_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_22_ce0_local = 1'b1;
    end else begin
        h_buf_22_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_22_we0_local = 1'b1;
    end else begin
        h_buf_22_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_23_ce0_local = 1'b1;
    end else begin
        h_buf_23_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_23_we0_local = 1'b1;
    end else begin
        h_buf_23_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_24_ce0_local = 1'b1;
    end else begin
        h_buf_24_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_24_we0_local = 1'b1;
    end else begin
        h_buf_24_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_25_ce0_local = 1'b1;
    end else begin
        h_buf_25_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_25_we0_local = 1'b1;
    end else begin
        h_buf_25_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_26_ce0_local = 1'b1;
    end else begin
        h_buf_26_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_26_we0_local = 1'b1;
    end else begin
        h_buf_26_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_27_ce0_local = 1'b1;
    end else begin
        h_buf_27_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_27_we0_local = 1'b1;
    end else begin
        h_buf_27_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_28_ce0_local = 1'b1;
    end else begin
        h_buf_28_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_28_we0_local = 1'b1;
    end else begin
        h_buf_28_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_29_ce0_local = 1'b1;
    end else begin
        h_buf_29_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_29_we0_local = 1'b1;
    end else begin
        h_buf_29_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_2_ce0_local = 1'b1;
    end else begin
        h_buf_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_2_we0_local = 1'b1;
    end else begin
        h_buf_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_30_ce0_local = 1'b1;
    end else begin
        h_buf_30_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_30_we0_local = 1'b1;
    end else begin
        h_buf_30_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_31_ce0_local = 1'b1;
    end else begin
        h_buf_31_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_31_we0_local = 1'b1;
    end else begin
        h_buf_31_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_3_ce0_local = 1'b1;
    end else begin
        h_buf_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_3_we0_local = 1'b1;
    end else begin
        h_buf_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_4_ce0_local = 1'b1;
    end else begin
        h_buf_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_4_we0_local = 1'b1;
    end else begin
        h_buf_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_5_ce0_local = 1'b1;
    end else begin
        h_buf_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_5_we0_local = 1'b1;
    end else begin
        h_buf_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_6_ce0_local = 1'b1;
    end else begin
        h_buf_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_6_we0_local = 1'b1;
    end else begin
        h_buf_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_7_ce0_local = 1'b1;
    end else begin
        h_buf_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_7_we0_local = 1'b1;
    end else begin
        h_buf_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_8_ce0_local = 1'b1;
    end else begin
        h_buf_8_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_8_we0_local = 1'b1;
    end else begin
        h_buf_8_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_9_ce0_local = 1'b1;
    end else begin
        h_buf_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_9_we0_local = 1'b1;
    end else begin
        h_buf_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_ce0_local = 1'b1;
    end else begin
        h_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        h_buf_we0_local = 1'b1;
    end else begin
        h_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_gmem2_0_RREADY = 1'b1;
    end else begin
        m_axi_gmem2_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln255_fu_687_p2 = (ap_sig_allocacmp_v_1 + 2'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_gmem2_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign h_buf_10_address0 = zext_ln255_fu_1018_p1;

assign h_buf_10_ce0 = h_buf_10_ce0_local;

assign h_buf_10_d0 = trunc_ln257_s_reg_1124;

assign h_buf_10_we0 = h_buf_10_we0_local;

assign h_buf_11_address0 = zext_ln255_fu_1018_p1;

assign h_buf_11_ce0 = h_buf_11_ce0_local;

assign h_buf_11_d0 = trunc_ln257_10_reg_1129;

assign h_buf_11_we0 = h_buf_11_we0_local;

assign h_buf_12_address0 = zext_ln255_fu_1018_p1;

assign h_buf_12_ce0 = h_buf_12_ce0_local;

assign h_buf_12_d0 = trunc_ln257_11_reg_1134;

assign h_buf_12_we0 = h_buf_12_we0_local;

assign h_buf_13_address0 = zext_ln255_fu_1018_p1;

assign h_buf_13_ce0 = h_buf_13_ce0_local;

assign h_buf_13_d0 = trunc_ln257_12_reg_1139;

assign h_buf_13_we0 = h_buf_13_we0_local;

assign h_buf_14_address0 = zext_ln255_fu_1018_p1;

assign h_buf_14_ce0 = h_buf_14_ce0_local;

assign h_buf_14_d0 = trunc_ln257_13_reg_1144;

assign h_buf_14_we0 = h_buf_14_we0_local;

assign h_buf_15_address0 = zext_ln255_fu_1018_p1;

assign h_buf_15_ce0 = h_buf_15_ce0_local;

assign h_buf_15_d0 = trunc_ln257_14_reg_1149;

assign h_buf_15_we0 = h_buf_15_we0_local;

assign h_buf_16_address0 = zext_ln255_fu_1018_p1;

assign h_buf_16_ce0 = h_buf_16_ce0_local;

assign h_buf_16_d0 = trunc_ln257_15_reg_1154;

assign h_buf_16_we0 = h_buf_16_we0_local;

assign h_buf_17_address0 = zext_ln255_fu_1018_p1;

assign h_buf_17_ce0 = h_buf_17_ce0_local;

assign h_buf_17_d0 = trunc_ln257_16_reg_1159;

assign h_buf_17_we0 = h_buf_17_we0_local;

assign h_buf_18_address0 = zext_ln255_fu_1018_p1;

assign h_buf_18_ce0 = h_buf_18_ce0_local;

assign h_buf_18_d0 = trunc_ln257_17_reg_1164;

assign h_buf_18_we0 = h_buf_18_we0_local;

assign h_buf_19_address0 = zext_ln255_fu_1018_p1;

assign h_buf_19_ce0 = h_buf_19_ce0_local;

assign h_buf_19_d0 = trunc_ln257_18_reg_1169;

assign h_buf_19_we0 = h_buf_19_we0_local;

assign h_buf_1_address0 = zext_ln255_fu_1018_p1;

assign h_buf_1_ce0 = h_buf_1_ce0_local;

assign h_buf_1_d0 = trunc_ln257_1_reg_1079;

assign h_buf_1_we0 = h_buf_1_we0_local;

assign h_buf_20_address0 = zext_ln255_fu_1018_p1;

assign h_buf_20_ce0 = h_buf_20_ce0_local;

assign h_buf_20_d0 = trunc_ln257_19_reg_1174;

assign h_buf_20_we0 = h_buf_20_we0_local;

assign h_buf_21_address0 = zext_ln255_fu_1018_p1;

assign h_buf_21_ce0 = h_buf_21_ce0_local;

assign h_buf_21_d0 = trunc_ln257_20_reg_1179;

assign h_buf_21_we0 = h_buf_21_we0_local;

assign h_buf_22_address0 = zext_ln255_fu_1018_p1;

assign h_buf_22_ce0 = h_buf_22_ce0_local;

assign h_buf_22_d0 = trunc_ln257_21_reg_1184;

assign h_buf_22_we0 = h_buf_22_we0_local;

assign h_buf_23_address0 = zext_ln255_fu_1018_p1;

assign h_buf_23_ce0 = h_buf_23_ce0_local;

assign h_buf_23_d0 = trunc_ln257_22_reg_1189;

assign h_buf_23_we0 = h_buf_23_we0_local;

assign h_buf_24_address0 = zext_ln255_fu_1018_p1;

assign h_buf_24_ce0 = h_buf_24_ce0_local;

assign h_buf_24_d0 = trunc_ln257_23_reg_1194;

assign h_buf_24_we0 = h_buf_24_we0_local;

assign h_buf_25_address0 = zext_ln255_fu_1018_p1;

assign h_buf_25_ce0 = h_buf_25_ce0_local;

assign h_buf_25_d0 = trunc_ln257_24_reg_1199;

assign h_buf_25_we0 = h_buf_25_we0_local;

assign h_buf_26_address0 = zext_ln255_fu_1018_p1;

assign h_buf_26_ce0 = h_buf_26_ce0_local;

assign h_buf_26_d0 = trunc_ln257_25_reg_1204;

assign h_buf_26_we0 = h_buf_26_we0_local;

assign h_buf_27_address0 = zext_ln255_fu_1018_p1;

assign h_buf_27_ce0 = h_buf_27_ce0_local;

assign h_buf_27_d0 = trunc_ln257_26_reg_1209;

assign h_buf_27_we0 = h_buf_27_we0_local;

assign h_buf_28_address0 = zext_ln255_fu_1018_p1;

assign h_buf_28_ce0 = h_buf_28_ce0_local;

assign h_buf_28_d0 = trunc_ln257_27_reg_1214;

assign h_buf_28_we0 = h_buf_28_we0_local;

assign h_buf_29_address0 = zext_ln255_fu_1018_p1;

assign h_buf_29_ce0 = h_buf_29_ce0_local;

assign h_buf_29_d0 = trunc_ln257_28_reg_1219;

assign h_buf_29_we0 = h_buf_29_we0_local;

assign h_buf_2_address0 = zext_ln255_fu_1018_p1;

assign h_buf_2_ce0 = h_buf_2_ce0_local;

assign h_buf_2_d0 = trunc_ln257_2_reg_1084;

assign h_buf_2_we0 = h_buf_2_we0_local;

assign h_buf_30_address0 = zext_ln255_fu_1018_p1;

assign h_buf_30_ce0 = h_buf_30_ce0_local;

assign h_buf_30_d0 = trunc_ln257_29_reg_1224;

assign h_buf_30_we0 = h_buf_30_we0_local;

assign h_buf_31_address0 = zext_ln255_fu_1018_p1;

assign h_buf_31_ce0 = h_buf_31_ce0_local;

assign h_buf_31_d0 = trunc_ln257_30_reg_1229;

assign h_buf_31_we0 = h_buf_31_we0_local;

assign h_buf_3_address0 = zext_ln255_fu_1018_p1;

assign h_buf_3_ce0 = h_buf_3_ce0_local;

assign h_buf_3_d0 = trunc_ln257_3_reg_1089;

assign h_buf_3_we0 = h_buf_3_we0_local;

assign h_buf_4_address0 = zext_ln255_fu_1018_p1;

assign h_buf_4_ce0 = h_buf_4_ce0_local;

assign h_buf_4_d0 = trunc_ln257_4_reg_1094;

assign h_buf_4_we0 = h_buf_4_we0_local;

assign h_buf_5_address0 = zext_ln255_fu_1018_p1;

assign h_buf_5_ce0 = h_buf_5_ce0_local;

assign h_buf_5_d0 = trunc_ln257_5_reg_1099;

assign h_buf_5_we0 = h_buf_5_we0_local;

assign h_buf_6_address0 = zext_ln255_fu_1018_p1;

assign h_buf_6_ce0 = h_buf_6_ce0_local;

assign h_buf_6_d0 = trunc_ln257_6_reg_1104;

assign h_buf_6_we0 = h_buf_6_we0_local;

assign h_buf_7_address0 = zext_ln255_fu_1018_p1;

assign h_buf_7_ce0 = h_buf_7_ce0_local;

assign h_buf_7_d0 = trunc_ln257_7_reg_1109;

assign h_buf_7_we0 = h_buf_7_we0_local;

assign h_buf_8_address0 = zext_ln255_fu_1018_p1;

assign h_buf_8_ce0 = h_buf_8_ce0_local;

assign h_buf_8_d0 = trunc_ln257_8_reg_1114;

assign h_buf_8_we0 = h_buf_8_we0_local;

assign h_buf_9_address0 = zext_ln255_fu_1018_p1;

assign h_buf_9_ce0 = h_buf_9_ce0_local;

assign h_buf_9_d0 = trunc_ln257_9_reg_1119;

assign h_buf_9_we0 = h_buf_9_we0_local;

assign h_buf_address0 = zext_ln255_fu_1018_p1;

assign h_buf_ce0 = h_buf_ce0_local;

assign h_buf_d0 = trunc_ln257_reg_1074;

assign h_buf_we0 = h_buf_we0_local;

assign icmp_ln255_fu_681_p2 = ((ap_sig_allocacmp_v_1 == 2'd2) ? 1'b1 : 1'b0);

assign m_axi_gmem2_0_ARADDR = 64'd0;

assign m_axi_gmem2_0_ARBURST = 2'd0;

assign m_axi_gmem2_0_ARCACHE = 4'd0;

assign m_axi_gmem2_0_ARID = 1'd0;

assign m_axi_gmem2_0_ARLEN = 32'd0;

assign m_axi_gmem2_0_ARLOCK = 2'd0;

assign m_axi_gmem2_0_ARPROT = 3'd0;

assign m_axi_gmem2_0_ARQOS = 4'd0;

assign m_axi_gmem2_0_ARREGION = 4'd0;

assign m_axi_gmem2_0_ARSIZE = 3'd0;

assign m_axi_gmem2_0_ARUSER = 1'd0;

assign m_axi_gmem2_0_ARVALID = 1'b0;

assign m_axi_gmem2_0_AWADDR = 64'd0;

assign m_axi_gmem2_0_AWBURST = 2'd0;

assign m_axi_gmem2_0_AWCACHE = 4'd0;

assign m_axi_gmem2_0_AWID = 1'd0;

assign m_axi_gmem2_0_AWLEN = 32'd0;

assign m_axi_gmem2_0_AWLOCK = 2'd0;

assign m_axi_gmem2_0_AWPROT = 3'd0;

assign m_axi_gmem2_0_AWQOS = 4'd0;

assign m_axi_gmem2_0_AWREGION = 4'd0;

assign m_axi_gmem2_0_AWSIZE = 3'd0;

assign m_axi_gmem2_0_AWUSER = 1'd0;

assign m_axi_gmem2_0_AWVALID = 1'b0;

assign m_axi_gmem2_0_BREADY = 1'b0;

assign m_axi_gmem2_0_WDATA = 512'd0;

assign m_axi_gmem2_0_WID = 1'd0;

assign m_axi_gmem2_0_WLAST = 1'b0;

assign m_axi_gmem2_0_WSTRB = 64'd0;

assign m_axi_gmem2_0_WUSER = 1'd0;

assign m_axi_gmem2_0_WVALID = 1'b0;

assign trunc_ln257_fu_704_p1 = m_axi_gmem2_0_RDATA[15:0];

assign zext_ln255_fu_1018_p1 = v_1_reg_1065_pp0_iter1_reg;

endmodule //integrated_gcn_spmm_compute_Pipeline_SPMM_LOAD_H
