-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity integrated_gcn_spmm_compute_Pipeline_SPMM_WRITE is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    result_fifo_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    result_fifo_full_n : IN STD_LOGIC;
    result_fifo_write : OUT STD_LOGIC;
    result_fifo_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    result_fifo_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_ce0 : OUT STD_LOGIC;
    acc_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_1_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_1_ce0 : OUT STD_LOGIC;
    acc_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_2_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_2_ce0 : OUT STD_LOGIC;
    acc_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_3_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_3_ce0 : OUT STD_LOGIC;
    acc_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_4_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_4_ce0 : OUT STD_LOGIC;
    acc_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_5_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_5_ce0 : OUT STD_LOGIC;
    acc_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_6_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_6_ce0 : OUT STD_LOGIC;
    acc_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_7_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_7_ce0 : OUT STD_LOGIC;
    acc_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_8_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_8_ce0 : OUT STD_LOGIC;
    acc_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_9_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_9_ce0 : OUT STD_LOGIC;
    acc_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_10_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_10_ce0 : OUT STD_LOGIC;
    acc_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_11_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_11_ce0 : OUT STD_LOGIC;
    acc_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_12_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_12_ce0 : OUT STD_LOGIC;
    acc_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_13_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_13_ce0 : OUT STD_LOGIC;
    acc_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_14_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_14_ce0 : OUT STD_LOGIC;
    acc_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_15_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_15_ce0 : OUT STD_LOGIC;
    acc_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_16_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_16_ce0 : OUT STD_LOGIC;
    acc_16_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_17_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_17_ce0 : OUT STD_LOGIC;
    acc_17_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_18_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_18_ce0 : OUT STD_LOGIC;
    acc_18_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_19_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_19_ce0 : OUT STD_LOGIC;
    acc_19_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_20_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_20_ce0 : OUT STD_LOGIC;
    acc_20_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_21_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_21_ce0 : OUT STD_LOGIC;
    acc_21_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_22_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_22_ce0 : OUT STD_LOGIC;
    acc_22_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_23_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_23_ce0 : OUT STD_LOGIC;
    acc_23_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_24_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_24_ce0 : OUT STD_LOGIC;
    acc_24_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_25_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_25_ce0 : OUT STD_LOGIC;
    acc_25_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_26_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_26_ce0 : OUT STD_LOGIC;
    acc_26_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_27_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_27_ce0 : OUT STD_LOGIC;
    acc_27_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_28_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_28_ce0 : OUT STD_LOGIC;
    acc_28_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_29_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_29_ce0 : OUT STD_LOGIC;
    acc_29_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_30_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_30_ce0 : OUT STD_LOGIC;
    acc_30_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    acc_31_address0 : OUT STD_LOGIC_VECTOR (0 downto 0);
    acc_31_ce0 : OUT STD_LOGIC;
    acc_31_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of integrated_gcn_spmm_compute_Pipeline_SPMM_WRITE is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln274_fu_639_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal result_fifo_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln274_fu_651_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal trunc_ln274_reg_1060 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln274_fu_663_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal f_fu_204 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal add_ln274_fu_645_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_f_2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal acc_ce0_local : STD_LOGIC;
    signal acc_1_ce0_local : STD_LOGIC;
    signal acc_2_ce0_local : STD_LOGIC;
    signal acc_3_ce0_local : STD_LOGIC;
    signal acc_4_ce0_local : STD_LOGIC;
    signal acc_5_ce0_local : STD_LOGIC;
    signal acc_6_ce0_local : STD_LOGIC;
    signal acc_7_ce0_local : STD_LOGIC;
    signal acc_8_ce0_local : STD_LOGIC;
    signal acc_9_ce0_local : STD_LOGIC;
    signal acc_10_ce0_local : STD_LOGIC;
    signal acc_11_ce0_local : STD_LOGIC;
    signal acc_12_ce0_local : STD_LOGIC;
    signal acc_13_ce0_local : STD_LOGIC;
    signal acc_14_ce0_local : STD_LOGIC;
    signal acc_15_ce0_local : STD_LOGIC;
    signal acc_16_ce0_local : STD_LOGIC;
    signal acc_17_ce0_local : STD_LOGIC;
    signal acc_18_ce0_local : STD_LOGIC;
    signal acc_19_ce0_local : STD_LOGIC;
    signal acc_20_ce0_local : STD_LOGIC;
    signal acc_21_ce0_local : STD_LOGIC;
    signal acc_22_ce0_local : STD_LOGIC;
    signal acc_23_ce0_local : STD_LOGIC;
    signal acc_24_ce0_local : STD_LOGIC;
    signal acc_25_ce0_local : STD_LOGIC;
    signal acc_26_ce0_local : STD_LOGIC;
    signal acc_27_ce0_local : STD_LOGIC;
    signal acc_28_ce0_local : STD_LOGIC;
    signal acc_29_ce0_local : STD_LOGIC;
    signal acc_30_ce0_local : STD_LOGIC;
    signal acc_31_ce0_local : STD_LOGIC;
    signal tmp_fu_655_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_704_p65 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_704_p67 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_2_fu_857_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln5_fu_847_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln276_fu_873_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln276_fu_877_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_4_fu_883_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_865_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln276_fu_891_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_911_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_fu_925_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln276_fu_897_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln276_1_fu_933_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln276_2_fu_939_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_903_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln276_fu_919_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln276_1_fu_953_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_1_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln276_fu_945_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln276_2_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_839_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln276_fu_985_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln276_3_fu_991_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln276_1_fu_965_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_2_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_4_fu_1003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln276_2_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln276_4_fu_1015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_3_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln276_5_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln276_1_fu_1035_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln276_2_fu_1027_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_704_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p51 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p53 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p55 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p57 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p59 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p61 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_704_p63 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component integrated_gcn_sparsemux_65_5_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (4 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (4 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (4 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (4 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (4 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (4 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (4 downto 0);
        din31_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        din9 : IN STD_LOGIC_VECTOR (31 downto 0);
        din10 : IN STD_LOGIC_VECTOR (31 downto 0);
        din11 : IN STD_LOGIC_VECTOR (31 downto 0);
        din12 : IN STD_LOGIC_VECTOR (31 downto 0);
        din13 : IN STD_LOGIC_VECTOR (31 downto 0);
        din14 : IN STD_LOGIC_VECTOR (31 downto 0);
        din15 : IN STD_LOGIC_VECTOR (31 downto 0);
        din16 : IN STD_LOGIC_VECTOR (31 downto 0);
        din17 : IN STD_LOGIC_VECTOR (31 downto 0);
        din18 : IN STD_LOGIC_VECTOR (31 downto 0);
        din19 : IN STD_LOGIC_VECTOR (31 downto 0);
        din20 : IN STD_LOGIC_VECTOR (31 downto 0);
        din21 : IN STD_LOGIC_VECTOR (31 downto 0);
        din22 : IN STD_LOGIC_VECTOR (31 downto 0);
        din23 : IN STD_LOGIC_VECTOR (31 downto 0);
        din24 : IN STD_LOGIC_VECTOR (31 downto 0);
        din25 : IN STD_LOGIC_VECTOR (31 downto 0);
        din26 : IN STD_LOGIC_VECTOR (31 downto 0);
        din27 : IN STD_LOGIC_VECTOR (31 downto 0);
        din28 : IN STD_LOGIC_VECTOR (31 downto 0);
        din29 : IN STD_LOGIC_VECTOR (31 downto 0);
        din30 : IN STD_LOGIC_VECTOR (31 downto 0);
        din31 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component integrated_gcn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_65_5_32_1_1_U1663 : component integrated_gcn_sparsemux_65_5_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 32,
        CASE1 => "00001",
        din1_WIDTH => 32,
        CASE2 => "00010",
        din2_WIDTH => 32,
        CASE3 => "00011",
        din3_WIDTH => 32,
        CASE4 => "00100",
        din4_WIDTH => 32,
        CASE5 => "00101",
        din5_WIDTH => 32,
        CASE6 => "00110",
        din6_WIDTH => 32,
        CASE7 => "00111",
        din7_WIDTH => 32,
        CASE8 => "01000",
        din8_WIDTH => 32,
        CASE9 => "01001",
        din9_WIDTH => 32,
        CASE10 => "01010",
        din10_WIDTH => 32,
        CASE11 => "01011",
        din11_WIDTH => 32,
        CASE12 => "01100",
        din12_WIDTH => 32,
        CASE13 => "01101",
        din13_WIDTH => 32,
        CASE14 => "01110",
        din14_WIDTH => 32,
        CASE15 => "01111",
        din15_WIDTH => 32,
        CASE16 => "10000",
        din16_WIDTH => 32,
        CASE17 => "10001",
        din17_WIDTH => 32,
        CASE18 => "10010",
        din18_WIDTH => 32,
        CASE19 => "10011",
        din19_WIDTH => 32,
        CASE20 => "10100",
        din20_WIDTH => 32,
        CASE21 => "10101",
        din21_WIDTH => 32,
        CASE22 => "10110",
        din22_WIDTH => 32,
        CASE23 => "10111",
        din23_WIDTH => 32,
        CASE24 => "11000",
        din24_WIDTH => 32,
        CASE25 => "11001",
        din25_WIDTH => 32,
        CASE26 => "11010",
        din26_WIDTH => 32,
        CASE27 => "11011",
        din27_WIDTH => 32,
        CASE28 => "11100",
        din28_WIDTH => 32,
        CASE29 => "11101",
        din29_WIDTH => 32,
        CASE30 => "11110",
        din30_WIDTH => 32,
        CASE31 => "11111",
        din31_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 5,
        dout_WIDTH => 32)
    port map (
        din0 => acc_q0,
        din1 => acc_1_q0,
        din2 => acc_2_q0,
        din3 => acc_3_q0,
        din4 => acc_4_q0,
        din5 => acc_5_q0,
        din6 => acc_6_q0,
        din7 => acc_7_q0,
        din8 => acc_8_q0,
        din9 => acc_9_q0,
        din10 => acc_10_q0,
        din11 => acc_11_q0,
        din12 => acc_12_q0,
        din13 => acc_13_q0,
        din14 => acc_14_q0,
        din15 => acc_15_q0,
        din16 => acc_16_q0,
        din17 => acc_17_q0,
        din18 => acc_18_q0,
        din19 => acc_19_q0,
        din20 => acc_20_q0,
        din21 => acc_21_q0,
        din22 => acc_22_q0,
        din23 => acc_23_q0,
        din24 => acc_24_q0,
        din25 => acc_25_q0,
        din26 => acc_26_q0,
        din27 => acc_27_q0,
        din28 => acc_28_q0,
        din29 => acc_29_q0,
        din30 => acc_30_q0,
        din31 => acc_31_q0,
        def => tmp_s_fu_704_p65,
        sel => trunc_ln274_reg_1060,
        dout => tmp_s_fu_704_p67);

    flow_control_loop_pipe_sequential_init_U : component integrated_gcn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    f_fu_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln274_fu_639_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    f_fu_204 <= add_ln274_fu_645_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    f_fu_204 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln274_reg_1060 <= trunc_ln274_fu_651_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_10_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_10_ce0 <= acc_10_ce0_local;

    acc_10_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_10_ce0_local <= ap_const_logic_1;
        else 
            acc_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_11_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_11_ce0 <= acc_11_ce0_local;

    acc_11_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_11_ce0_local <= ap_const_logic_1;
        else 
            acc_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_12_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_12_ce0 <= acc_12_ce0_local;

    acc_12_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_12_ce0_local <= ap_const_logic_1;
        else 
            acc_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_13_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_13_ce0 <= acc_13_ce0_local;

    acc_13_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_13_ce0_local <= ap_const_logic_1;
        else 
            acc_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_14_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_14_ce0 <= acc_14_ce0_local;

    acc_14_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_14_ce0_local <= ap_const_logic_1;
        else 
            acc_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_15_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_15_ce0 <= acc_15_ce0_local;

    acc_15_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_15_ce0_local <= ap_const_logic_1;
        else 
            acc_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_16_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_16_ce0 <= acc_16_ce0_local;

    acc_16_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_16_ce0_local <= ap_const_logic_1;
        else 
            acc_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_17_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_17_ce0 <= acc_17_ce0_local;

    acc_17_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_17_ce0_local <= ap_const_logic_1;
        else 
            acc_17_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_18_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_18_ce0 <= acc_18_ce0_local;

    acc_18_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_18_ce0_local <= ap_const_logic_1;
        else 
            acc_18_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_19_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_19_ce0 <= acc_19_ce0_local;

    acc_19_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_19_ce0_local <= ap_const_logic_1;
        else 
            acc_19_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_1_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_1_ce0 <= acc_1_ce0_local;

    acc_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_1_ce0_local <= ap_const_logic_1;
        else 
            acc_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_20_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_20_ce0 <= acc_20_ce0_local;

    acc_20_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_20_ce0_local <= ap_const_logic_1;
        else 
            acc_20_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_21_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_21_ce0 <= acc_21_ce0_local;

    acc_21_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_21_ce0_local <= ap_const_logic_1;
        else 
            acc_21_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_22_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_22_ce0 <= acc_22_ce0_local;

    acc_22_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_22_ce0_local <= ap_const_logic_1;
        else 
            acc_22_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_23_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_23_ce0 <= acc_23_ce0_local;

    acc_23_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_23_ce0_local <= ap_const_logic_1;
        else 
            acc_23_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_24_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_24_ce0 <= acc_24_ce0_local;

    acc_24_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_24_ce0_local <= ap_const_logic_1;
        else 
            acc_24_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_25_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_25_ce0 <= acc_25_ce0_local;

    acc_25_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_25_ce0_local <= ap_const_logic_1;
        else 
            acc_25_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_26_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_26_ce0 <= acc_26_ce0_local;

    acc_26_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_26_ce0_local <= ap_const_logic_1;
        else 
            acc_26_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_27_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_27_ce0 <= acc_27_ce0_local;

    acc_27_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_27_ce0_local <= ap_const_logic_1;
        else 
            acc_27_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_28_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_28_ce0 <= acc_28_ce0_local;

    acc_28_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_28_ce0_local <= ap_const_logic_1;
        else 
            acc_28_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_29_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_29_ce0 <= acc_29_ce0_local;

    acc_29_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_29_ce0_local <= ap_const_logic_1;
        else 
            acc_29_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_2_ce0 <= acc_2_ce0_local;

    acc_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_2_ce0_local <= ap_const_logic_1;
        else 
            acc_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_30_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_30_ce0 <= acc_30_ce0_local;

    acc_30_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_30_ce0_local <= ap_const_logic_1;
        else 
            acc_30_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_31_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_31_ce0 <= acc_31_ce0_local;

    acc_31_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_31_ce0_local <= ap_const_logic_1;
        else 
            acc_31_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_3_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_3_ce0 <= acc_3_ce0_local;

    acc_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_3_ce0_local <= ap_const_logic_1;
        else 
            acc_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_4_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_4_ce0 <= acc_4_ce0_local;

    acc_4_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_4_ce0_local <= ap_const_logic_1;
        else 
            acc_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_5_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_5_ce0 <= acc_5_ce0_local;

    acc_5_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_5_ce0_local <= ap_const_logic_1;
        else 
            acc_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_6_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_6_ce0 <= acc_6_ce0_local;

    acc_6_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_6_ce0_local <= ap_const_logic_1;
        else 
            acc_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_7_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_7_ce0 <= acc_7_ce0_local;

    acc_7_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_7_ce0_local <= ap_const_logic_1;
        else 
            acc_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_8_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_8_ce0 <= acc_8_ce0_local;

    acc_8_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_8_ce0_local <= ap_const_logic_1;
        else 
            acc_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_9_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_9_ce0 <= acc_9_ce0_local;

    acc_9_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_9_ce0_local <= ap_const_logic_1;
        else 
            acc_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    acc_address0 <= zext_ln274_fu_663_p1(1 - 1 downto 0);
    acc_ce0 <= acc_ce0_local;

    acc_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            acc_ce0_local <= ap_const_logic_1;
        else 
            acc_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    add_ln274_fu_645_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_f_2) + unsigned(ap_const_lv7_1));
    add_ln276_fu_877_p2 <= std_logic_vector(unsigned(trunc_ln5_fu_847_p4) + unsigned(zext_ln276_fu_873_p1));
    and_ln276_1_fu_959_p2 <= (xor_ln276_1_fu_953_p2 and icmp_ln276_fu_919_p2);
    and_ln276_2_fu_973_p2 <= (icmp_ln276_1_fu_933_p2 and and_ln276_fu_897_p2);
    and_ln276_3_fu_997_p2 <= (xor_ln276_3_fu_991_p2 and or_ln276_fu_985_p2);
    and_ln276_4_fu_1003_p2 <= (tmp_4_fu_883_p3 and select_ln276_1_fu_965_p3);
    and_ln276_5_fu_1021_p2 <= (xor_ln276_4_fu_1015_p2 and tmp_1_fu_839_p3);
    and_ln276_fu_897_p2 <= (xor_ln276_fu_891_p2 and tmp_3_fu_865_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state2_pp0_stage0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(result_fifo_full_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (result_fifo_full_n = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln274_fu_639_p2)
    begin
        if (((icmp_ln274_fu_639_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_f_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, f_fu_204, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_f_2 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_f_2 <= f_fu_204;
        end if; 
    end process;

    icmp_ln274_fu_639_p2 <= "1" when (ap_sig_allocacmp_f_2 = ap_const_lv7_40) else "0";
    icmp_ln276_1_fu_933_p2 <= "1" when (tmp_7_fu_925_p3 = ap_const_lv6_3F) else "0";
    icmp_ln276_2_fu_939_p2 <= "1" when (tmp_7_fu_925_p3 = ap_const_lv6_0) else "0";
    icmp_ln276_fu_919_p2 <= "1" when (tmp_6_fu_911_p3 = ap_const_lv5_1F) else "0";
    or_ln276_1_fu_1035_p2 <= (and_ln276_5_fu_1021_p2 or and_ln276_3_fu_997_p2);
    or_ln276_2_fu_1009_p2 <= (and_ln276_4_fu_1003_p2 or and_ln276_2_fu_973_p2);
    or_ln276_fu_985_p2 <= (xor_ln276_2_fu_979_p2 or tmp_4_fu_883_p3);

    result_fifo_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, result_fifo_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            result_fifo_blk_n <= result_fifo_full_n;
        else 
            result_fifo_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    result_fifo_din <= 
        select_ln276_2_fu_1027_p3 when (or_ln276_1_fu_1035_p2(0) = '1') else 
        add_ln276_fu_877_p2;

    result_fifo_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            result_fifo_write <= ap_const_logic_1;
        else 
            result_fifo_write <= ap_const_logic_0;
        end if; 
    end process;

    select_ln276_1_fu_965_p3 <= 
        and_ln276_1_fu_959_p2 when (and_ln276_fu_897_p2(0) = '1') else 
        icmp_ln276_1_fu_933_p2;
    select_ln276_2_fu_1027_p3 <= 
        ap_const_lv16_7FFF when (and_ln276_3_fu_997_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln276_fu_945_p3 <= 
        icmp_ln276_1_fu_933_p2 when (and_ln276_fu_897_p2(0) = '1') else 
        icmp_ln276_2_fu_939_p2;
    tmp_1_fu_839_p3 <= tmp_s_fu_704_p67(31 downto 31);
    tmp_2_fu_857_p3 <= tmp_s_fu_704_p67(9 downto 9);
    tmp_3_fu_865_p3 <= tmp_s_fu_704_p67(25 downto 25);
    tmp_4_fu_883_p3 <= add_ln276_fu_877_p2(15 downto 15);
    tmp_5_fu_903_p3 <= tmp_s_fu_704_p67(26 downto 26);
    tmp_6_fu_911_p3 <= tmp_s_fu_704_p67(31 downto 27);
    tmp_7_fu_925_p3 <= tmp_s_fu_704_p67(31 downto 26);
    tmp_fu_655_p3 <= ap_sig_allocacmp_f_2(5 downto 5);
    tmp_s_fu_704_p65 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    trunc_ln274_fu_651_p1 <= ap_sig_allocacmp_f_2(5 - 1 downto 0);
    trunc_ln5_fu_847_p4 <= tmp_s_fu_704_p67(25 downto 10);
    xor_ln276_1_fu_953_p2 <= (tmp_5_fu_903_p3 xor ap_const_lv1_1);
    xor_ln276_2_fu_979_p2 <= (select_ln276_fu_945_p3 xor ap_const_lv1_1);
    xor_ln276_3_fu_991_p2 <= (tmp_1_fu_839_p3 xor ap_const_lv1_1);
    xor_ln276_4_fu_1015_p2 <= (or_ln276_2_fu_1009_p2 xor ap_const_lv1_1);
    xor_ln276_fu_891_p2 <= (tmp_4_fu_883_p3 xor ap_const_lv1_1);
    zext_ln274_fu_663_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_655_p3),64));
    zext_ln276_fu_873_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_857_p3),16));
end behav;
