-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity integrated_gcn_gemm_stage is
port (
    m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem0_0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    X : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_WREADY : IN STD_LOGIC;
    m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RVALID : IN STD_LOGIC;
    m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem1_0_RLAST : IN STD_LOGIC;
    m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BVALID : IN STD_LOGIC;
    m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    W : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
    m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_WREADY : IN STD_LOGIC;
    m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
    m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
    m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RVALID : IN STD_LOGIC;
    m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
    m_axi_gmem2_0_RLAST : IN STD_LOGIC;
    m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BVALID : IN STD_LOGIC;
    m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
    m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    H_temp : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    X_ap_vld : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    W_ap_vld : IN STD_LOGIC;
    H_temp_ap_vld : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of integrated_gcn_gemm_stage is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv512_lc_1 : STD_LOGIC_VECTOR (511 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal gemm_read_X_U0_ap_start : STD_LOGIC;
    signal gemm_read_X_U0_ap_done : STD_LOGIC;
    signal gemm_read_X_U0_ap_continue : STD_LOGIC;
    signal gemm_read_X_U0_ap_idle : STD_LOGIC;
    signal gemm_read_X_U0_ap_ready : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_AWVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WLAST : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARVALID : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_X_U0_m_axi_gmem0_0_RREADY : STD_LOGIC;
    signal gemm_read_X_U0_m_axi_gmem0_0_BREADY : STD_LOGIC;
    signal gemm_read_X_U0_X_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_X_U0_X_stream_write : STD_LOGIC;
    signal gemm_read_X_U0_start_out : STD_LOGIC;
    signal gemm_read_X_U0_start_write : STD_LOGIC;
    signal gemm_read_W_U0_ap_start : STD_LOGIC;
    signal gemm_read_W_U0_ap_done : STD_LOGIC;
    signal gemm_read_W_U0_ap_continue : STD_LOGIC;
    signal gemm_read_W_U0_ap_idle : STD_LOGIC;
    signal gemm_read_W_U0_ap_ready : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_AWVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WLAST : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARVALID : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_read_W_U0_m_axi_gmem1_0_RREADY : STD_LOGIC;
    signal gemm_read_W_U0_m_axi_gmem1_0_BREADY : STD_LOGIC;
    signal gemm_read_W_U0_W_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_read_W_U0_W_stream_write : STD_LOGIC;
    signal gemm_compute_U0_ap_start : STD_LOGIC;
    signal gemm_compute_U0_ap_done : STD_LOGIC;
    signal gemm_compute_U0_ap_continue : STD_LOGIC;
    signal gemm_compute_U0_ap_idle : STD_LOGIC;
    signal gemm_compute_U0_ap_ready : STD_LOGIC;
    signal gemm_compute_U0_start_out : STD_LOGIC;
    signal gemm_compute_U0_start_write : STD_LOGIC;
    signal gemm_compute_U0_X_stream_read : STD_LOGIC;
    signal gemm_compute_U0_W_stream_read : STD_LOGIC;
    signal gemm_compute_U0_XW_stream_din : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_compute_U0_XW_stream_write : STD_LOGIC;
    signal gemm_compute_U0_XW_stream_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_compute_U0_XW_stream_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_ap_start : STD_LOGIC;
    signal gemm_write_U0_ap_done : STD_LOGIC;
    signal gemm_write_U0_ap_continue : STD_LOGIC;
    signal gemm_write_U0_ap_idle : STD_LOGIC;
    signal gemm_write_U0_ap_ready : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_AWVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_WDATA : STD_LOGIC_VECTOR (511 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WSTRB : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WLAST : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARVALID : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal gemm_write_U0_m_axi_gmem2_0_RREADY : STD_LOGIC;
    signal gemm_write_U0_m_axi_gmem2_0_BREADY : STD_LOGIC;
    signal gemm_write_U0_XW_stream_read : STD_LOGIC;
    signal X_stream_full_n : STD_LOGIC;
    signal X_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal X_stream_empty_n : STD_LOGIC;
    signal X_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal X_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal W_stream_full_n : STD_LOGIC;
    signal W_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal W_stream_empty_n : STD_LOGIC;
    signal W_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal W_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal XW_stream_full_n : STD_LOGIC;
    signal XW_stream_dout : STD_LOGIC_VECTOR (511 downto 0);
    signal XW_stream_empty_n : STD_LOGIC;
    signal XW_stream_num_data_valid : STD_LOGIC_VECTOR (4 downto 0);
    signal XW_stream_fifo_cap : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_gemm_read_X_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_gemm_read_X_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_gemm_read_W_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_gemm_read_W_U0_ap_ready : STD_LOGIC;
    signal start_for_gemm_compute_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_compute_U0_full_n : STD_LOGIC;
    signal start_for_gemm_compute_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_compute_U0_empty_n : STD_LOGIC;
    signal start_for_gemm_write_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_write_U0_full_n : STD_LOGIC;
    signal start_for_gemm_write_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_gemm_write_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component integrated_gcn_gemm_read_X IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem0_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem0_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_WREADY : IN STD_LOGIC;
        m_axi_gmem0_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem0_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem0_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem0_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem0_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem0_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem0_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem0_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem0_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RVALID : IN STD_LOGIC;
        m_axi_gmem0_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem0_0_RLAST : IN STD_LOGIC;
        m_axi_gmem0_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem0_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BVALID : IN STD_LOGIC;
        m_axi_gmem0_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem0_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem0_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem0_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        X_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        X_stream_full_n : IN STD_LOGIC;
        X_stream_write : OUT STD_LOGIC;
        X_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        X_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        X : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component integrated_gcn_gemm_read_W IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem1_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem1_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_WREADY : IN STD_LOGIC;
        m_axi_gmem1_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem1_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem1_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem1_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem1_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem1_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem1_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem1_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem1_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RVALID : IN STD_LOGIC;
        m_axi_gmem1_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem1_0_RLAST : IN STD_LOGIC;
        m_axi_gmem1_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem1_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BVALID : IN STD_LOGIC;
        m_axi_gmem1_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem1_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem1_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem1_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        W_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        W_stream_full_n : IN STD_LOGIC;
        W_stream_write : OUT STD_LOGIC;
        W_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        W : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component integrated_gcn_gemm_compute IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        X_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        X_stream_empty_n : IN STD_LOGIC;
        X_stream_read : OUT STD_LOGIC;
        X_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        X_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        W_stream_empty_n : IN STD_LOGIC;
        W_stream_read : OUT STD_LOGIC;
        W_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        W_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        XW_stream_din : OUT STD_LOGIC_VECTOR (511 downto 0);
        XW_stream_full_n : IN STD_LOGIC;
        XW_stream_write : OUT STD_LOGIC;
        XW_stream_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        XW_stream_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component integrated_gcn_gemm_write IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem2_0_AWVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_AWREADY : IN STD_LOGIC;
        m_axi_gmem2_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_WREADY : IN STD_LOGIC;
        m_axi_gmem2_0_WDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem2_0_WSTRB : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_WLAST : OUT STD_LOGIC;
        m_axi_gmem2_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARVALID : OUT STD_LOGIC;
        m_axi_gmem2_0_ARREADY : IN STD_LOGIC;
        m_axi_gmem2_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem2_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem2_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem2_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem2_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RVALID : IN STD_LOGIC;
        m_axi_gmem2_0_RREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_RDATA : IN STD_LOGIC_VECTOR (511 downto 0);
        m_axi_gmem2_0_RLAST : IN STD_LOGIC;
        m_axi_gmem2_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem2_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BVALID : IN STD_LOGIC;
        m_axi_gmem2_0_BREADY : OUT STD_LOGIC;
        m_axi_gmem2_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem2_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem2_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        XW_stream_dout : IN STD_LOGIC_VECTOR (511 downto 0);
        XW_stream_empty_n : IN STD_LOGIC;
        XW_stream_read : OUT STD_LOGIC;
        XW_stream_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        XW_stream_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        H_temp : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component integrated_gcn_fifo_w512_d16_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (511 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (511 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (4 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;


    component integrated_gcn_start_for_gemm_compute_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component integrated_gcn_start_for_gemm_write_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    gemm_read_X_U0 : component integrated_gcn_gemm_read_X
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => gemm_read_X_U0_ap_start,
        start_full_n => start_for_gemm_compute_U0_full_n,
        ap_done => gemm_read_X_U0_ap_done,
        ap_continue => gemm_read_X_U0_ap_continue,
        ap_idle => gemm_read_X_U0_ap_idle,
        ap_ready => gemm_read_X_U0_ap_ready,
        m_axi_gmem0_0_AWVALID => gemm_read_X_U0_m_axi_gmem0_0_AWVALID,
        m_axi_gmem0_0_AWREADY => ap_const_logic_0,
        m_axi_gmem0_0_AWADDR => gemm_read_X_U0_m_axi_gmem0_0_AWADDR,
        m_axi_gmem0_0_AWID => gemm_read_X_U0_m_axi_gmem0_0_AWID,
        m_axi_gmem0_0_AWLEN => gemm_read_X_U0_m_axi_gmem0_0_AWLEN,
        m_axi_gmem0_0_AWSIZE => gemm_read_X_U0_m_axi_gmem0_0_AWSIZE,
        m_axi_gmem0_0_AWBURST => gemm_read_X_U0_m_axi_gmem0_0_AWBURST,
        m_axi_gmem0_0_AWLOCK => gemm_read_X_U0_m_axi_gmem0_0_AWLOCK,
        m_axi_gmem0_0_AWCACHE => gemm_read_X_U0_m_axi_gmem0_0_AWCACHE,
        m_axi_gmem0_0_AWPROT => gemm_read_X_U0_m_axi_gmem0_0_AWPROT,
        m_axi_gmem0_0_AWQOS => gemm_read_X_U0_m_axi_gmem0_0_AWQOS,
        m_axi_gmem0_0_AWREGION => gemm_read_X_U0_m_axi_gmem0_0_AWREGION,
        m_axi_gmem0_0_AWUSER => gemm_read_X_U0_m_axi_gmem0_0_AWUSER,
        m_axi_gmem0_0_WVALID => gemm_read_X_U0_m_axi_gmem0_0_WVALID,
        m_axi_gmem0_0_WREADY => ap_const_logic_0,
        m_axi_gmem0_0_WDATA => gemm_read_X_U0_m_axi_gmem0_0_WDATA,
        m_axi_gmem0_0_WSTRB => gemm_read_X_U0_m_axi_gmem0_0_WSTRB,
        m_axi_gmem0_0_WLAST => gemm_read_X_U0_m_axi_gmem0_0_WLAST,
        m_axi_gmem0_0_WID => gemm_read_X_U0_m_axi_gmem0_0_WID,
        m_axi_gmem0_0_WUSER => gemm_read_X_U0_m_axi_gmem0_0_WUSER,
        m_axi_gmem0_0_ARVALID => gemm_read_X_U0_m_axi_gmem0_0_ARVALID,
        m_axi_gmem0_0_ARREADY => m_axi_gmem0_0_ARREADY,
        m_axi_gmem0_0_ARADDR => gemm_read_X_U0_m_axi_gmem0_0_ARADDR,
        m_axi_gmem0_0_ARID => gemm_read_X_U0_m_axi_gmem0_0_ARID,
        m_axi_gmem0_0_ARLEN => gemm_read_X_U0_m_axi_gmem0_0_ARLEN,
        m_axi_gmem0_0_ARSIZE => gemm_read_X_U0_m_axi_gmem0_0_ARSIZE,
        m_axi_gmem0_0_ARBURST => gemm_read_X_U0_m_axi_gmem0_0_ARBURST,
        m_axi_gmem0_0_ARLOCK => gemm_read_X_U0_m_axi_gmem0_0_ARLOCK,
        m_axi_gmem0_0_ARCACHE => gemm_read_X_U0_m_axi_gmem0_0_ARCACHE,
        m_axi_gmem0_0_ARPROT => gemm_read_X_U0_m_axi_gmem0_0_ARPROT,
        m_axi_gmem0_0_ARQOS => gemm_read_X_U0_m_axi_gmem0_0_ARQOS,
        m_axi_gmem0_0_ARREGION => gemm_read_X_U0_m_axi_gmem0_0_ARREGION,
        m_axi_gmem0_0_ARUSER => gemm_read_X_U0_m_axi_gmem0_0_ARUSER,
        m_axi_gmem0_0_RVALID => m_axi_gmem0_0_RVALID,
        m_axi_gmem0_0_RREADY => gemm_read_X_U0_m_axi_gmem0_0_RREADY,
        m_axi_gmem0_0_RDATA => m_axi_gmem0_0_RDATA,
        m_axi_gmem0_0_RLAST => m_axi_gmem0_0_RLAST,
        m_axi_gmem0_0_RID => m_axi_gmem0_0_RID,
        m_axi_gmem0_0_RFIFONUM => m_axi_gmem0_0_RFIFONUM,
        m_axi_gmem0_0_RUSER => m_axi_gmem0_0_RUSER,
        m_axi_gmem0_0_RRESP => m_axi_gmem0_0_RRESP,
        m_axi_gmem0_0_BVALID => ap_const_logic_0,
        m_axi_gmem0_0_BREADY => gemm_read_X_U0_m_axi_gmem0_0_BREADY,
        m_axi_gmem0_0_BRESP => ap_const_lv2_0,
        m_axi_gmem0_0_BID => ap_const_lv1_0,
        m_axi_gmem0_0_BUSER => ap_const_lv1_0,
        X_stream_din => gemm_read_X_U0_X_stream_din,
        X_stream_full_n => X_stream_full_n,
        X_stream_write => gemm_read_X_U0_X_stream_write,
        X_stream_num_data_valid => X_stream_num_data_valid,
        X_stream_fifo_cap => X_stream_fifo_cap,
        start_out => gemm_read_X_U0_start_out,
        start_write => gemm_read_X_U0_start_write,
        X => X);

    gemm_read_W_U0 : component integrated_gcn_gemm_read_W
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => gemm_read_W_U0_ap_start,
        ap_done => gemm_read_W_U0_ap_done,
        ap_continue => gemm_read_W_U0_ap_continue,
        ap_idle => gemm_read_W_U0_ap_idle,
        ap_ready => gemm_read_W_U0_ap_ready,
        m_axi_gmem1_0_AWVALID => gemm_read_W_U0_m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY => ap_const_logic_0,
        m_axi_gmem1_0_AWADDR => gemm_read_W_U0_m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID => gemm_read_W_U0_m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN => gemm_read_W_U0_m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE => gemm_read_W_U0_m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST => gemm_read_W_U0_m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK => gemm_read_W_U0_m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE => gemm_read_W_U0_m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT => gemm_read_W_U0_m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS => gemm_read_W_U0_m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION => gemm_read_W_U0_m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER => gemm_read_W_U0_m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID => gemm_read_W_U0_m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY => ap_const_logic_0,
        m_axi_gmem1_0_WDATA => gemm_read_W_U0_m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB => gemm_read_W_U0_m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST => gemm_read_W_U0_m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID => gemm_read_W_U0_m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER => gemm_read_W_U0_m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID => gemm_read_W_U0_m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY => m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR => gemm_read_W_U0_m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID => gemm_read_W_U0_m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN => gemm_read_W_U0_m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE => gemm_read_W_U0_m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST => gemm_read_W_U0_m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK => gemm_read_W_U0_m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE => gemm_read_W_U0_m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT => gemm_read_W_U0_m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS => gemm_read_W_U0_m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION => gemm_read_W_U0_m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER => gemm_read_W_U0_m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID => m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY => gemm_read_W_U0_m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA => m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST => m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID => m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM => m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER => m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP => m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID => ap_const_logic_0,
        m_axi_gmem1_0_BREADY => gemm_read_W_U0_m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP => ap_const_lv2_0,
        m_axi_gmem1_0_BID => ap_const_lv1_0,
        m_axi_gmem1_0_BUSER => ap_const_lv1_0,
        W_stream_din => gemm_read_W_U0_W_stream_din,
        W_stream_full_n => W_stream_full_n,
        W_stream_write => gemm_read_W_U0_W_stream_write,
        W_stream_num_data_valid => W_stream_num_data_valid,
        W_stream_fifo_cap => W_stream_fifo_cap,
        W => W);

    gemm_compute_U0 : component integrated_gcn_gemm_compute
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => gemm_compute_U0_ap_start,
        start_full_n => start_for_gemm_write_U0_full_n,
        ap_done => gemm_compute_U0_ap_done,
        ap_continue => gemm_compute_U0_ap_continue,
        ap_idle => gemm_compute_U0_ap_idle,
        ap_ready => gemm_compute_U0_ap_ready,
        start_out => gemm_compute_U0_start_out,
        start_write => gemm_compute_U0_start_write,
        X_stream_dout => X_stream_dout,
        X_stream_empty_n => X_stream_empty_n,
        X_stream_read => gemm_compute_U0_X_stream_read,
        X_stream_num_data_valid => X_stream_num_data_valid,
        X_stream_fifo_cap => X_stream_fifo_cap,
        W_stream_dout => W_stream_dout,
        W_stream_empty_n => W_stream_empty_n,
        W_stream_read => gemm_compute_U0_W_stream_read,
        W_stream_num_data_valid => W_stream_num_data_valid,
        W_stream_fifo_cap => W_stream_fifo_cap,
        XW_stream_din => gemm_compute_U0_XW_stream_din,
        XW_stream_full_n => XW_stream_full_n,
        XW_stream_write => gemm_compute_U0_XW_stream_write,
        XW_stream_num_data_valid => gemm_compute_U0_XW_stream_num_data_valid,
        XW_stream_fifo_cap => gemm_compute_U0_XW_stream_fifo_cap);

    gemm_write_U0 : component integrated_gcn_gemm_write
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => gemm_write_U0_ap_start,
        ap_done => gemm_write_U0_ap_done,
        ap_continue => gemm_write_U0_ap_continue,
        ap_idle => gemm_write_U0_ap_idle,
        ap_ready => gemm_write_U0_ap_ready,
        m_axi_gmem2_0_AWVALID => gemm_write_U0_m_axi_gmem2_0_AWVALID,
        m_axi_gmem2_0_AWREADY => m_axi_gmem2_0_AWREADY,
        m_axi_gmem2_0_AWADDR => gemm_write_U0_m_axi_gmem2_0_AWADDR,
        m_axi_gmem2_0_AWID => gemm_write_U0_m_axi_gmem2_0_AWID,
        m_axi_gmem2_0_AWLEN => gemm_write_U0_m_axi_gmem2_0_AWLEN,
        m_axi_gmem2_0_AWSIZE => gemm_write_U0_m_axi_gmem2_0_AWSIZE,
        m_axi_gmem2_0_AWBURST => gemm_write_U0_m_axi_gmem2_0_AWBURST,
        m_axi_gmem2_0_AWLOCK => gemm_write_U0_m_axi_gmem2_0_AWLOCK,
        m_axi_gmem2_0_AWCACHE => gemm_write_U0_m_axi_gmem2_0_AWCACHE,
        m_axi_gmem2_0_AWPROT => gemm_write_U0_m_axi_gmem2_0_AWPROT,
        m_axi_gmem2_0_AWQOS => gemm_write_U0_m_axi_gmem2_0_AWQOS,
        m_axi_gmem2_0_AWREGION => gemm_write_U0_m_axi_gmem2_0_AWREGION,
        m_axi_gmem2_0_AWUSER => gemm_write_U0_m_axi_gmem2_0_AWUSER,
        m_axi_gmem2_0_WVALID => gemm_write_U0_m_axi_gmem2_0_WVALID,
        m_axi_gmem2_0_WREADY => m_axi_gmem2_0_WREADY,
        m_axi_gmem2_0_WDATA => gemm_write_U0_m_axi_gmem2_0_WDATA,
        m_axi_gmem2_0_WSTRB => gemm_write_U0_m_axi_gmem2_0_WSTRB,
        m_axi_gmem2_0_WLAST => gemm_write_U0_m_axi_gmem2_0_WLAST,
        m_axi_gmem2_0_WID => gemm_write_U0_m_axi_gmem2_0_WID,
        m_axi_gmem2_0_WUSER => gemm_write_U0_m_axi_gmem2_0_WUSER,
        m_axi_gmem2_0_ARVALID => gemm_write_U0_m_axi_gmem2_0_ARVALID,
        m_axi_gmem2_0_ARREADY => ap_const_logic_0,
        m_axi_gmem2_0_ARADDR => gemm_write_U0_m_axi_gmem2_0_ARADDR,
        m_axi_gmem2_0_ARID => gemm_write_U0_m_axi_gmem2_0_ARID,
        m_axi_gmem2_0_ARLEN => gemm_write_U0_m_axi_gmem2_0_ARLEN,
        m_axi_gmem2_0_ARSIZE => gemm_write_U0_m_axi_gmem2_0_ARSIZE,
        m_axi_gmem2_0_ARBURST => gemm_write_U0_m_axi_gmem2_0_ARBURST,
        m_axi_gmem2_0_ARLOCK => gemm_write_U0_m_axi_gmem2_0_ARLOCK,
        m_axi_gmem2_0_ARCACHE => gemm_write_U0_m_axi_gmem2_0_ARCACHE,
        m_axi_gmem2_0_ARPROT => gemm_write_U0_m_axi_gmem2_0_ARPROT,
        m_axi_gmem2_0_ARQOS => gemm_write_U0_m_axi_gmem2_0_ARQOS,
        m_axi_gmem2_0_ARREGION => gemm_write_U0_m_axi_gmem2_0_ARREGION,
        m_axi_gmem2_0_ARUSER => gemm_write_U0_m_axi_gmem2_0_ARUSER,
        m_axi_gmem2_0_RVALID => ap_const_logic_0,
        m_axi_gmem2_0_RREADY => gemm_write_U0_m_axi_gmem2_0_RREADY,
        m_axi_gmem2_0_RDATA => ap_const_lv512_lc_1,
        m_axi_gmem2_0_RLAST => ap_const_logic_0,
        m_axi_gmem2_0_RID => ap_const_lv1_0,
        m_axi_gmem2_0_RFIFONUM => ap_const_lv9_0,
        m_axi_gmem2_0_RUSER => ap_const_lv1_0,
        m_axi_gmem2_0_RRESP => ap_const_lv2_0,
        m_axi_gmem2_0_BVALID => m_axi_gmem2_0_BVALID,
        m_axi_gmem2_0_BREADY => gemm_write_U0_m_axi_gmem2_0_BREADY,
        m_axi_gmem2_0_BRESP => m_axi_gmem2_0_BRESP,
        m_axi_gmem2_0_BID => m_axi_gmem2_0_BID,
        m_axi_gmem2_0_BUSER => m_axi_gmem2_0_BUSER,
        XW_stream_dout => XW_stream_dout,
        XW_stream_empty_n => XW_stream_empty_n,
        XW_stream_read => gemm_write_U0_XW_stream_read,
        XW_stream_num_data_valid => XW_stream_num_data_valid,
        XW_stream_fifo_cap => XW_stream_fifo_cap,
        H_temp => H_temp);

    X_stream_U : component integrated_gcn_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_read_X_U0_X_stream_din,
        if_full_n => X_stream_full_n,
        if_write => gemm_read_X_U0_X_stream_write,
        if_dout => X_stream_dout,
        if_empty_n => X_stream_empty_n,
        if_read => gemm_compute_U0_X_stream_read,
        if_num_data_valid => X_stream_num_data_valid,
        if_fifo_cap => X_stream_fifo_cap);

    W_stream_U : component integrated_gcn_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_read_W_U0_W_stream_din,
        if_full_n => W_stream_full_n,
        if_write => gemm_read_W_U0_W_stream_write,
        if_dout => W_stream_dout,
        if_empty_n => W_stream_empty_n,
        if_read => gemm_compute_U0_W_stream_read,
        if_num_data_valid => W_stream_num_data_valid,
        if_fifo_cap => W_stream_fifo_cap);

    XW_stream_U : component integrated_gcn_fifo_w512_d16_A
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => gemm_compute_U0_XW_stream_din,
        if_full_n => XW_stream_full_n,
        if_write => gemm_compute_U0_XW_stream_write,
        if_dout => XW_stream_dout,
        if_empty_n => XW_stream_empty_n,
        if_read => gemm_write_U0_XW_stream_read,
        if_num_data_valid => XW_stream_num_data_valid,
        if_fifo_cap => XW_stream_fifo_cap);

    start_for_gemm_compute_U0_U : component integrated_gcn_start_for_gemm_compute_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_gemm_compute_U0_din,
        if_full_n => start_for_gemm_compute_U0_full_n,
        if_write => gemm_read_X_U0_start_write,
        if_dout => start_for_gemm_compute_U0_dout,
        if_empty_n => start_for_gemm_compute_U0_empty_n,
        if_read => gemm_compute_U0_ap_ready);

    start_for_gemm_write_U0_U : component integrated_gcn_start_for_gemm_write_U0
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_gemm_write_U0_din,
        if_full_n => start_for_gemm_write_U0_full_n,
        if_write => gemm_compute_U0_start_write,
        if_dout => start_for_gemm_write_U0_dout,
        if_empty_n => start_for_gemm_write_U0_empty_n,
        if_read => gemm_write_U0_ap_ready);





    ap_sync_reg_gemm_read_W_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_gemm_read_W_U0_ap_ready <= ap_sync_gemm_read_W_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_gemm_read_X_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_gemm_read_X_U0_ap_ready <= ap_sync_gemm_read_X_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_ready_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_sync_ready <= (not(ap_sync_ready) and ap_sync_gemm_read_X_U0_ap_ready and ap_sync_gemm_read_W_U0_ap_ready and ap_start);
        end if;
    end process;
    ap_done <= gemm_write_U0_ap_done;
    ap_idle <= (gemm_write_U0_ap_idle and gemm_read_X_U0_ap_idle and gemm_read_W_U0_ap_idle and gemm_compute_U0_ap_idle);
    ap_ready <= ap_sync_ready;
    ap_sync_gemm_read_W_U0_ap_ready <= (gemm_read_W_U0_ap_ready or ap_sync_reg_gemm_read_W_U0_ap_ready);
    ap_sync_gemm_read_X_U0_ap_ready <= (gemm_read_X_U0_ap_ready or ap_sync_reg_gemm_read_X_U0_ap_ready);
    gemm_compute_U0_XW_stream_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(XW_stream_fifo_cap),5))),32));
    gemm_compute_U0_XW_stream_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(XW_stream_num_data_valid),5))),32));
    gemm_compute_U0_ap_continue <= ap_const_logic_1;
    gemm_compute_U0_ap_start <= start_for_gemm_compute_U0_empty_n;
    gemm_read_W_U0_ap_continue <= ap_const_logic_1;
    gemm_read_W_U0_ap_start <= ((ap_sync_reg_gemm_read_W_U0_ap_ready xor ap_const_logic_1) and not(ap_sync_ready) and ap_start);
    gemm_read_X_U0_ap_continue <= ap_const_logic_1;
    gemm_read_X_U0_ap_start <= ((ap_sync_reg_gemm_read_X_U0_ap_ready xor ap_const_logic_1) and not(ap_sync_ready) and ap_start);
    gemm_write_U0_ap_continue <= ap_continue;
    gemm_write_U0_ap_start <= start_for_gemm_write_U0_empty_n;
    m_axi_gmem0_0_ARADDR <= gemm_read_X_U0_m_axi_gmem0_0_ARADDR;
    m_axi_gmem0_0_ARBURST <= gemm_read_X_U0_m_axi_gmem0_0_ARBURST;
    m_axi_gmem0_0_ARCACHE <= gemm_read_X_U0_m_axi_gmem0_0_ARCACHE;
    m_axi_gmem0_0_ARID <= gemm_read_X_U0_m_axi_gmem0_0_ARID;
    m_axi_gmem0_0_ARLEN <= gemm_read_X_U0_m_axi_gmem0_0_ARLEN;
    m_axi_gmem0_0_ARLOCK <= gemm_read_X_U0_m_axi_gmem0_0_ARLOCK;
    m_axi_gmem0_0_ARPROT <= gemm_read_X_U0_m_axi_gmem0_0_ARPROT;
    m_axi_gmem0_0_ARQOS <= gemm_read_X_U0_m_axi_gmem0_0_ARQOS;
    m_axi_gmem0_0_ARREGION <= gemm_read_X_U0_m_axi_gmem0_0_ARREGION;
    m_axi_gmem0_0_ARSIZE <= gemm_read_X_U0_m_axi_gmem0_0_ARSIZE;
    m_axi_gmem0_0_ARUSER <= gemm_read_X_U0_m_axi_gmem0_0_ARUSER;
    m_axi_gmem0_0_ARVALID <= gemm_read_X_U0_m_axi_gmem0_0_ARVALID;
    m_axi_gmem0_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_0_BREADY <= ap_const_logic_0;
    m_axi_gmem0_0_RREADY <= gemm_read_X_U0_m_axi_gmem0_0_RREADY;
    m_axi_gmem0_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem0_0_WID <= ap_const_lv1_0;
    m_axi_gmem0_0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem0_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_0_WVALID <= ap_const_logic_0;
    m_axi_gmem1_0_ARADDR <= gemm_read_W_U0_m_axi_gmem1_0_ARADDR;
    m_axi_gmem1_0_ARBURST <= gemm_read_W_U0_m_axi_gmem1_0_ARBURST;
    m_axi_gmem1_0_ARCACHE <= gemm_read_W_U0_m_axi_gmem1_0_ARCACHE;
    m_axi_gmem1_0_ARID <= gemm_read_W_U0_m_axi_gmem1_0_ARID;
    m_axi_gmem1_0_ARLEN <= gemm_read_W_U0_m_axi_gmem1_0_ARLEN;
    m_axi_gmem1_0_ARLOCK <= gemm_read_W_U0_m_axi_gmem1_0_ARLOCK;
    m_axi_gmem1_0_ARPROT <= gemm_read_W_U0_m_axi_gmem1_0_ARPROT;
    m_axi_gmem1_0_ARQOS <= gemm_read_W_U0_m_axi_gmem1_0_ARQOS;
    m_axi_gmem1_0_ARREGION <= gemm_read_W_U0_m_axi_gmem1_0_ARREGION;
    m_axi_gmem1_0_ARSIZE <= gemm_read_W_U0_m_axi_gmem1_0_ARSIZE;
    m_axi_gmem1_0_ARUSER <= gemm_read_W_U0_m_axi_gmem1_0_ARUSER;
    m_axi_gmem1_0_ARVALID <= gemm_read_W_U0_m_axi_gmem1_0_ARVALID;
    m_axi_gmem1_0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem1_0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem1_0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem1_0_AWID <= ap_const_lv1_0;
    m_axi_gmem1_0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem1_0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem1_0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem1_0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem1_0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem1_0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem1_0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_AWVALID <= ap_const_logic_0;
    m_axi_gmem1_0_BREADY <= ap_const_logic_0;
    m_axi_gmem1_0_RREADY <= gemm_read_W_U0_m_axi_gmem1_0_RREADY;
    m_axi_gmem1_0_WDATA <= ap_const_lv512_lc_1;
    m_axi_gmem1_0_WID <= ap_const_lv1_0;
    m_axi_gmem1_0_WLAST <= ap_const_logic_0;
    m_axi_gmem1_0_WSTRB <= ap_const_lv64_0;
    m_axi_gmem1_0_WUSER <= ap_const_lv1_0;
    m_axi_gmem1_0_WVALID <= ap_const_logic_0;
    m_axi_gmem2_0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem2_0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem2_0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem2_0_ARID <= ap_const_lv1_0;
    m_axi_gmem2_0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem2_0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem2_0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem2_0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem2_0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem2_0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem2_0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem2_0_ARVALID <= ap_const_logic_0;
    m_axi_gmem2_0_AWADDR <= gemm_write_U0_m_axi_gmem2_0_AWADDR;
    m_axi_gmem2_0_AWBURST <= gemm_write_U0_m_axi_gmem2_0_AWBURST;
    m_axi_gmem2_0_AWCACHE <= gemm_write_U0_m_axi_gmem2_0_AWCACHE;
    m_axi_gmem2_0_AWID <= gemm_write_U0_m_axi_gmem2_0_AWID;
    m_axi_gmem2_0_AWLEN <= gemm_write_U0_m_axi_gmem2_0_AWLEN;
    m_axi_gmem2_0_AWLOCK <= gemm_write_U0_m_axi_gmem2_0_AWLOCK;
    m_axi_gmem2_0_AWPROT <= gemm_write_U0_m_axi_gmem2_0_AWPROT;
    m_axi_gmem2_0_AWQOS <= gemm_write_U0_m_axi_gmem2_0_AWQOS;
    m_axi_gmem2_0_AWREGION <= gemm_write_U0_m_axi_gmem2_0_AWREGION;
    m_axi_gmem2_0_AWSIZE <= gemm_write_U0_m_axi_gmem2_0_AWSIZE;
    m_axi_gmem2_0_AWUSER <= gemm_write_U0_m_axi_gmem2_0_AWUSER;
    m_axi_gmem2_0_AWVALID <= gemm_write_U0_m_axi_gmem2_0_AWVALID;
    m_axi_gmem2_0_BREADY <= gemm_write_U0_m_axi_gmem2_0_BREADY;
    m_axi_gmem2_0_RREADY <= ap_const_logic_0;
    m_axi_gmem2_0_WDATA <= gemm_write_U0_m_axi_gmem2_0_WDATA;
    m_axi_gmem2_0_WID <= gemm_write_U0_m_axi_gmem2_0_WID;
    m_axi_gmem2_0_WLAST <= gemm_write_U0_m_axi_gmem2_0_WLAST;
    m_axi_gmem2_0_WSTRB <= gemm_write_U0_m_axi_gmem2_0_WSTRB;
    m_axi_gmem2_0_WUSER <= gemm_write_U0_m_axi_gmem2_0_WUSER;
    m_axi_gmem2_0_WVALID <= gemm_write_U0_m_axi_gmem2_0_WVALID;
    start_for_gemm_compute_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_gemm_write_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
