[hls]
relative_roots=/home/nat/dev/trinners/mai_proj/hls/thesis-gcn-accelerator/vitis/integrated_gcn/naive_spmm_kernel
# Inferred from syn.compile.pipeline_loops=64
syn.directive.pipeline=naive_spmm_stage/SPMM_NNZ 
syn.directive.pipeline=naive_spmm_stage/SPMM_INIT 
syn.directive.pipeline=naive_spmm_stage/SPMM_WRITE 


